### PR TITLE
Fix write_partisn_input() iteration order

### PR DESCRIPTION
**Pull request by elliottbiondo**
Partisn uses what we have been calling "zyx" iteration order, where "x" changes fastest. Evidence of this is found in #750. The `write_partisn_input()` function erroneously writes zones in "zxy" (not a typo) order. This was previously not discovered because unit tests did not test the iteration order and I only recently ran a significantly asymmetric problem for these effects to be noticed.

This PR corrects the iteration order by doing a few matrix operations. @kkiesling is planning on refactoring this function and I imagine it will be greatly simplified by changing the `structured_ordering` attribute on `Mesh`. I have also added unit test. Below is a large, asymmetric problem that I was able to run now that the iteration order is correct.
right_order

### CODE REVIEW

**Comment by elliottbiondo** [comment]
Image of unit test, with asymmetry in all 3 dimensions.
unit_test

**Comment by scopatz** [comment]
Who do you want to review this?

**Comment by elliottbiondo** [comment]
I think @kkiesling should review.

**Comment by scopatz** [comment]
Great :) I am super busy with NEUPs

**Comment by elliottbiondo** [comment]
Good luck!

**Comment by scopatz** [comment]
Thanks!

**Comment by kkiesling** [comment]
Looks exactly as we discussed earlier for a temporary fix until I can refactor. I'll merge when travis-ci finishes.

**Comment by kkiesling** [comment]
Hmm it says that the test you wrote @elliottbiondo doesn't pass.

**Comment by elliottbiondo** [comment]
Yep, I forgot to add the unit test geometry. Fixed.

**Pull request merged**
