### PR TITLE
Style changes suggested by pylint and flake8 review

### PR DESCRIPTION
**Pull request by apthorpe**
This batch of edits consist of 'semi-cosmetic' changes to 68 pure Python files (Cython files were untouched.) Most changes involve changing whitespace and adding comments and docstrings. In some cases `%` string interpolation syntax was replaced with `str.format()`, long strings were broken across lines, and 2-to-3 support was improved with imports from `__future__`. Missing docstrings were filled in with placeholders, i.e. `""" TBD """`.

In cases of indentation style conflicts between flake8 and pylint, flake8 style was used and pylint warnings were explicitly suppressed with `# pylint: disable=bad-indentation`.

I'm still having issues testing in my environment (mainly with `pyne._utils`) so I haven't been able to test as thoroughly as I'd like. There shouldn't be any functional changes in this block of edits.

### CODE REVIEW

**Review by katyhuff — COMMENTED** [review]
Very cool @apthorpe . 
This looks good to me, except I'm a little concerned with the TBD docstrings. I am fine including them if we also create a new issue that, effectively, seeks to fill in every single one of them with meaningful information. I have a student I can put on this task, if needed.

The continuous integration checks should confirm/deny that these changes haven't broken anything. We'll wait for that before pulling. 

Those are my two cents. Let's also wait a bit to see if anyone else has any comments.

**Comment by apthorpe** [comment]
My intention with the TBD docstrings was to fill them in with time, either as I understood the code or as others got irritated by seeing them; the end result should be to have meaningful internal documentation, not just to make pylint happy. This way there's a visual 'nag' to add docstrings, rather than the invisible nag of warnings from pylint.

I can make a first pass at adding one issue per file for resolving TBD docstrings so that each gets tracked; the first step is to make a quick estimate of how many issues that entails (less than 68 IIRC)

**Comment by katyhuff** [comment]
It looks like there are some failing tests. Do you have time to track down what is causing these MOAB problems, etc? I assume it's probably just a random accidental character or something. https://travis-ci.org/pyne/pyne/builds/238792169?utm_source=github_status&utm_medium=notification

**Comment by apthorpe** [comment]
Two tests are failing: test_dagmc.py and test_partisn.py, both with `Unrecognized option: ""!` errors from MOAB. Looks like some random binary crud is being interpreted as options to MOAB. Line-ending issue or uninitialized variable?

I'll check through the source to see if I added any debris; I don't think so, but nobody ever does...

**Comment by apthorpe** [comment]
I found some embedded tabs in `pyne/material.pyx` but nothing odd in the files I changed. I'll look at what test_dagmc.py and test_partisn.py imports, back out changes that I made to those files, and put together a new pull request minus those files.

I've had a little more success testing; I built Python from source, put it into a virtualenv, and was able to get a few more tests to run but there's still far too much brokenness. At the moment, `from pyne import dagmc` fails for no obvious reason so I still can't replicate the TravisCI failures locally. I should probably just blow everything away, grab the head of `develop`, and try to build, test, and install it. I'm still having fights between `setup.py install --user` and virtualenv over what PYTHONPATH should be set to (IMO it's a red flag that I even have to touch this). I have zero faith that my build environment is set up correctly and I have no idea what I should be doing differently.

**Comment by gonuke** [comment]
Apologies @apthorpe that this was never merged.  It is a very welcome contribution and one we have not yet undertaken ourselves.  Unfortunately, it is now very outdated by updates in the code base.

I am not sure if there is bandwidth to repeat this linting process within the push to a next release any day now, but we'd welcome it as something we will pay attention to immediately following.

If you don't have the bandwidth to contribute this again based on the new code - and I understand that you may have neither bandwidth nor motivation given how this PR lingered - we can take it up ourselves, but it would be great to have your contributions recognized.

**Pull request closed without merging**
