### PR TITLE
Added fortran writing/reading capability

### PR DESCRIPTION
**Pull request by ngranda**
This PR: 
Adds a fortran writer and a fortran reader along with the necessary scripts to use this capability. These files live under the fortranformat folder. 
The license for use has been added under the pyne license.text file

### CODE REVIEW

**Comment by gonuke** [comment]
I think it would be good to add a really simple test - basically to show that it can be called from this installation.  Perhaps just use the writer to write a few things to a binary file and then use the reader to read them back and check that it does the round trip successfully.  Nothing too complicated.

**Comment by gonuke** [comment]
@ngranda This is failing because it can't find your module in CI.  Might check with others who know something about PyNE CI

**Comment by ngranda** [comment]
I believe I fixed it. The module should be added to the build now.

**Comment by gonuke** [comment]
Thanks @ngranda - looks good

**Pull request merged**
