### PR TITLE
following changes to allow nuclear data to be retrieved from memory, …

### PR DESCRIPTION
**Pull request by makeclean**
…expand elements was broken, now fixed, needed refactor

### CODE REVIEW

**Comment by scopatz** [comment]
CI fail :(

**Comment by makeclean** [comment]
Yeah, but not due to me I think. The failure was wrt to a specific gfortran version not being found. Right? Or am I misreading the log?

**Comment by scopatz** [comment]
Yeah, this seems to be a gfortran version error for some reason I do not understand.  It might be time to switch to CircleCI, where we would have more control over these kinds of things.

**Comment by makeclean** [comment]
I think the problem is that one of the dependencies pulled in by Conda (I'm thinking scipy) may be out of date, I'll create an issue tomorrow and start some deeper digging.

**Comment by gonuke** [comment]
@makeclean - this was a very long time ago now.... but do you know if this was fixed with the simpler change in #1117?  If not, we might want to revisit this soon.  We have a little more attention in PyNE so we can probably move this along more quickly.

**Comment by makeclean** [comment]
I think this was fixed in #1117

**Pull request closed without merging**
