### PR TITLE
Moab52 fix activation responses

### PR DESCRIPTION
**Pull request by zxkjack123**
## Description
Describe your changes in detail.
Change the `h5diff` command in the `test_activation_responses.py`. Compare specific tags.

## Motivation and Context
This PR fixes the test failure in the `test_activation_responses.py` when MOAB5.2 is used. This is the solution to https://github.com/pyne/pyne/issues/1325.

## Changes
Bug fix.

## Behavior
The current code fails the test in `test_activation_responses.py` when MOAB5.2 is used. Now it passes all the tests. 

## Other Information
The reason of the failure is the change of the `/tstt/tags/GLOBAL_ID`. It changed from -1 to 0. It is compared in the previous tests, however,  it is not relevent to the tags of responses.

## Changelog file
All pull requests are required to update the [CHANGELOG](https://github.com/pyne/pyne/blob/develop/CHANGELOG.rst) file with the PR.  Your update can take different forms including:

* creating a new entry describing your change, including a reference to this pull request number
* adding a reference to your pull request number to an exist entry if that entry can include your changes

### CODE REVIEW

**Comment by gonuke** [comment]
@bam241 - the changelog test is failing for some reason?

**Comment by bam241** [comment]
@gonuke 
this is very strange, I was not able to restart the failed jobs, (the command were working locally...) because it ran from @zxkjack123 circle account not the PyNE one.

I copied the branch and  PRed as is, to see if I could play with the CI separately from this PR,  it restarted the changelog test... and passed.
CI is clever enough to figure out that the tests running for my COPY PR are the same as this one, so it updates the status here as they finish for my PR....
This "give" me the permission to rerun the failing ones...

I don't understand why on the first place @zxkjack123 tests were not running as on CIrcleCI as PYNE but as `zxkjack123` (see the link [here](https://app.circleci.com/pipelines/github/zxkjack123/pyne/557/workflows/571d38a4-918e-4e80-8394-0083d905990e/jobs/5974) results of one of the tests before my copy PR...)

**Comment by gonuke** [comment]
It also seems that something you did has rebased this too???

The next step is to test this with MOAB 5.2, since CI is still using MOAB 5.1.  We need a "how to" page on how to tests against updated dependencies because I think we'll face this often.  

Note: there is now a MOAB 5.2.1 so we might as well use that.

**Comment by zxkjack123** [comment]
@gonuke Yes, I rebased this PR. This PR contains only the change in `test_activation_responses.py`. The previous version of this PR was based on `AI-Pranto/moab-version`. 
I rebased it on the current `develop` as this PR is the prerequisite of the `moab-version` and easier to review.

**Comment by gonuke** [comment]
Thanks @zxkjack123.  FYI - we no longer need a news file.  We are doing it with changes to the CHANGELOG directly to make releases easier.

**Comment by zxkjack123** [comment]
Update: Removed the unnecessary news file.

**Comment by gonuke** [comment]
I've confirmed that this fixes the problem with MOAB 5.2.x.  Since this fix also works with MOAB 5.1.0 (per CI) , I'm merging now.  I can see that the changelog has changed and I'm not sure why the test is failing.

**Comment by gonuke** [comment]
Thanks @zxkjack123 - I'm sure it would have taken us much longer to find this difference.

**Pull request merged**
