### PR TITLE
Add README outlining dev roadmap for GT-CADIS scripts

### LINKED ISSUE #978: Top-level design of workflow support script(s)
* Create a directory for GT-CADIS files
* Move outline from project description to a README in that directory
* include a link to @biondo's figshare DOI

### PR DESCRIPTION
**Pull request by gonuke**
Fixes #978

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @gonuke - can you please rebase / merge from develop so that CI will pass.

**Comment by gonuke** [comment]
@cadangelo @ngranda @moatazharb - can you review this quickly and decide whether or not it is still necessary and/or correct.
1. Have you written other documents that supersede this now to guide your work? (If so, I'll close this)
2. If this is still generally useful, is it correct? (If not, please either make PRs into this branch or comments on this PR)
Thanks!

**Comment by gonuke** [comment]
In trying to remedy an installation error, I realized that there really is no logical place to put a transient document like this in PyNE.  I also don't think there necessarily should be.

One option would be to use this document as a placeholder for the ultimate users guide document, but it isn't really a users guide document, so it would be odd if placed there.

I think it might make the most sense to withdraw this PR and just link to the document that lives in my repo from the project description.

Any other thoughts, suggestions? @scopatz @cadangelo @ngranda @moatazharb

**Comment by gonuke** [comment]
Closing this - the document is still available in the link the project.

**Pull request closed without merging**
