### PR TITLE
minor regex updates to ensdf parser

### PR DESCRIPTION
**Pull request by crbates**
ensure there are no levels listed as nan

### CODE REVIEW

**Comment by crbates** [comment]
proton/neutron resonance levels are still not reported properly. I think this could be a quick fix but I don't think it should hold up this PR.

**Comment by scopatz** [comment]
Does this need a new nuc data?

**Comment by crbates** [comment]
it doesn't need a new pre-built or state_map but it does require a `nuc_data_make --clean 1`.

**Comment by scopatz** [comment]
Also, how is our CI working?

**Comment by scopatz** [comment]
Looks good. Waiting for CI.

**Comment by scopatz** [comment]
mac qhell

**Comment by scopatz** [comment]
Thanks again, @crbates!

**Comment by crbates** [comment]
thanks for reviewing @scopatz!

**Pull request merged**
