### PR TITLE
Decay Amalgamation fix

### PR DESCRIPTION
**Pull request by scopatz**
Needed for  https://github.com/cyclus/cyclus/pull/1439

CC @FlanFlanagan @pyne/core

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
Getting this error. 

```
-- The Fortran compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /home/robert/miniconda3/bin/gfortran
-- Check for working Fortran compiler: /home/robert/miniconda3/bin/gfortran  -- broken
CMake Error at /home/robert/miniconda3/share/cmake-3.10/Modules/CMakeTestFortranCompiler.cmake:45 (message):
  The Fortran compiler

    "/home/robert/miniconda3/bin/gfortran"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/robert/pyne/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_37fe1/fast"
    /usr/bin/make -f CMakeFiles/cmTC_37fe1.dir/build.make CMakeFiles/cmTC_37fe1.dir/build
    make[1]: Entering directory '/home/robert/pyne/build/CMakeFiles/CMakeTmp'
    Building Fortran object CMakeFiles/cmTC_37fe1.dir/testFortranCompiler.f.o
    /home/robert/miniconda3/bin/gfortran    -c /home/robert/pyne/build/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_37fe1.dir/testFortranCompiler.f.o
    Linking Fortran executable cmTC_37fe1
    /home/robert/miniconda3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_37fe1.dir/link.txt --verbose=1
    /home/robert/miniconda3/bin/gfortran      CMakeFiles/cmTC_37fe1.dir/testFortranCompiler.f.o  -o cmTC_37fe1 
    /home/robert/miniconda3/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libgfortran.a(main.o): In function `_gfortrani_find_addr2line':
    (.text._gfortrani_find_addr2line+0xe): undefined reference to `__secure_getenv'
    /home/robert/miniconda3/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libgfortran.a(unix.o): In function `_gfortrani_open_external':
    (.text._gfortrani_open_external+0xa6): undefined reference to `__secure_getenv'
    collect2: error: ld returned 1 exit status
    CMakeFiles/cmTC_37fe1.dir/build.make:97: recipe for target 'cmTC_37fe1' failed
    make[1]: *** [cmTC_37fe1] Error 1
    make[1]: Leaving directory '/home/robert/pyne/build/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_37fe1/fast' failed
    make: *** [cmTC_37fe1/fast] Error 2
    

```

**Comment by scopatz** [comment]
This seems unrelated. Can you try a clean build please?

**Comment by FlanFlanagan** [comment]
That is from a clean build. I think it is unrelated as well. Unfortunately until I fix that issue I can't fully test the PR.

**Comment by scopatz** [comment]
Can you post the full output and the run command please?

**Comment by scopatz** [comment]
Also try conda installing or removing moab.

**Comment by FlanFlanagan** [comment]
Issue fixed.

**Pull request merged**
