### PR TITLE
update for CI

### PR DESCRIPTION
**Pull request by scopatz**
Don't need to bootstrap anymore

### CODE REVIEW

**Comment by scopatz** [comment]
CC @pyne/developers

**Comment by ljacobson64** [comment]
Why don't we need this anymore?

**Comment by ljacobson64** [comment]
@scopatz

**Comment by scopatz** [comment]
Sorry I missed this! We don't need this anymore because I updated the docker containers to include the latest bateman solver and data.  Thus we don't need to regenerated it in CI for the tests to pass.

**Comment by ljacobson64** [comment]
I see!

**Pull request merged**
