### PR TITLE
IMeshTag about (N, 1) shaped array

### PR DESCRIPTION
**Pull request by zxkjack123**
This pull request contains the modification described in issue #967 . 

Major change:

1. When adding a tag from a (N, 1) array (tag size is 1), the default IMeshTag data for each volume element is set to be an array but not a number.

### CODE REVIEW

**Comment by pshriwise** [comment]
I'm curious about what this means for #965, is it still necessary after these changes?

**Comment by zxkjack123** [comment]
@pshriwise Actually, if this pull request merged into PyNE, #965 is no longer necessary. 

Keeping #965 won't make error, but I will modify #965 to delete unnecessary code if this pull request merged first.

**Comment by pshriwise** [comment]
@zxkjack123 good. I think making the change here is best if it doesn't cause tests to fail. @scopatz should probably take a quick look at this as well to make sure this is going into the right location.

That sounds good regarding #965. The formatting improvements and additional test should be kept I think.

**Comment by zxkjack123** [comment]
@pshriwise As you can see, I didn't make changes in test files in this pull request. But I tested this change with the condition of add a tag with array (N, 1). This test function is in #965 . I didn't add that test function here to avoid mess up the pull requests sequences.

**Comment by pshriwise** [comment]
This is what I was referring to. The test in PR #965 :smile: I think we're on the same page.

**Pull request closed without merging**
