### PR TITLE
brief comment fixes

### PR DESCRIPTION
**Pull request by rachelslaybaugh**

### CODE REVIEW

**Comment by elliottbiondo** [comment]
I get the following error when trying to open this on the VB:

`Unreadable Notebook: Unsupported JSON nbformat version 4 (supported version: 3)`

Looks like the same problem on my laptop. Not sure how easy a fix this is.

**Comment by elliottbiondo** [comment]
Luckily all notebooks seem to be running on the VB right now without issue. Assuming the changes you've made here are small you might want to just redo these changes from the VB and submit a new PR.

**Comment by rachelslaybaugh** [comment]
Did taking out the ipython notebook stuff fix it?

**Comment by elliottbiondo** [comment]
Yep! As soon as CI passes I will merge.

**Pull request merged**
