### PR TITLE
Build system improvements

### PR DESCRIPTION
**Pull request by scopatz**
CC @FlanFlanagan @andrewryh @pyne/core

### CODE REVIEW

**Comment by gonuke** [comment]
I think this needs a rebase after other build system changes, then I can take another look....

**Comment by scopatz** [comment]
Updated and conflicts resolved

**Comment by scopatz** [comment]
Thanks for pointing out @gonuke!

**Comment by scopatz** [comment]
ping @gonuke @FlanFlanagan

**Comment by gonuke** [comment]
Looks good to me - thanks @scopatz

**Pull request merged**
