### PR TITLE
forward decl for decayer in case of amalgamation

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by scopatz** [comment]
How were you compiling the test? Sorry to get back to this so late.

**Comment by crbates** [comment]
I made a basic amalgamation test shell script + makefile + helloworld.cpp. I will put it up on github tonight if I can find it.

**Comment by scopatz** [comment]
Thanks!

**Comment by crbates** [comment]
@scopatz  here's the test program I used https://github.com/crbates/pyne-cpp

**Comment by scopatz** [comment]
Hi @crbates! Thanks this clears things up. The reason this fails is because it is not downloading and compiling the decay functionality. That brings up an important question about what to do... In cyclus we have dummy files:

* https://github.com/cyclus/cyclus/blob/develop/src/_pyne_decay.h
* https://github.com/cyclus/cyclus/blob/develop/src/_pyne_decay.cc

Perhaps we should have more fully fledged dummies that throw an error if they are called.  I think a major problem is that we don't want to amalgamate decay, since it needs to be compiled with `-O0`. Ideas?

**Comment by crbates** [comment]
can't we just use the existing dummy decay files in PyNE during the amalgamation step?

**Comment by crbates** [comment]
Also I agree there should be some error or warning if the `nuc_id` isn't in the switch case list.

**Comment by scopatz** [comment]
> can't we just use the existing dummy decay files in PyNE during the amalgamation step?

And this is why you are the smartest developer alive, @crbates :).  I must have put these dummies in there, but I totally forgot that they existed. Why I remember the cyclus ones is beyond me. I must be going mad.

> Also I agree there should be some error or warning if the nuc_id isn't in the switch case list.

That should probably be in the decaygen. Mind if that is a separate PR?

**Comment by scopatz** [comment]
Ok, so say that we use the dummies. Then someone does try to download and (statically) link in the real files, won't the symbols collide?

**Comment by scopatz** [comment]
Maybe we could have pound-defined variable encapsulating the dummies.  It doesn't really change the header at all.

**Comment by crbates** [comment]
I think this is the right idea. I mean the use case is needing to amalgamate instead of linking to `libpyne.*` and using the headers. 

>> Also I agree there should be some error or warning if the nuc_id isn't in the switch case list.

> That should probably be in the decaygen. Mind if that is a separate PR?

I think that makes sense.

**Comment by scopatz** [comment]
Ok! I think that this is ready to go. I have put in a PR to https://github.com/crbates/pyne-cpp/pull/1 which now works for me.  Also do you think that this test repo should live in the pyne org. Seems super useful.

**Comment by scopatz** [comment]
Also, super huge thanks.

**Comment by crbates** [comment]
we seem to be in the queue nether.

**Comment by crbates** [comment]
I'm going to PR the python 3 one separately. thanks @scopatz!

**Pull request merged**
