### PR TITLE
Update endf_reader.ipynb

### LINKED ISSUE #1226: ENDF-reader example is broken
Trying to run the [endf-reader example](https://pyne.io/examples/endf_reader.html) as-is on the website gives the following error when attempting to load the U235 data file:
`u235 = Library("U235-VII.txt")`
`xs_data = u235.get_xs(922350000, 16)[0]`
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-6fce4d341e13> in <module>()
----> 1 u235 = Library("U235-VII.txt")
      2 xs_data = u235.get_xs(922350000, 16)[0]
      3 
      4 #h1 = Library("H1-VII_mod.txt")
      5 ## args are nuclide ID, MT number, isotope ID (defaults to nuclide ID)

endf.pyx in pyne.endf.Library.__init__()

endf.pyx in pyne.endf.Library._read_headers()

ValueError: invalid literal for int() with base 10: '0  0'
```
After noticing that the printout from the evaluation info on the website was different to the files downloaded from the linked source, I tracked down a copy of the original files at [this location](http://ukrndc.kinr.kiev.ua/!!!site_ukrndc/DATA/ENDF-7_1/092_U_235). After comparing the two I found that the updated files seem be missing a trailing '0' in the first line of the file:
*File at the [example location](https://t2.lanl.gov/nis/data/data/ENDFB-VII-neutron/U/235)*
```
                                                                     1 0  0
 9.223500+4 2.330248+2          1          1          0          79228 1451    1
 0.000000+0 1.000000+0          0          0          0          69228 1451    2
 1.000000+0 2.000000+7          0          0         10          79228 1451    3
 0.000000+0 0.000000+0          0          0        733        1249228 1451    4
```
*Original file now at [this location](http://ukrndc.kinr.kiev.ua/!!!site_ukrndc/DATA/ENDF-7_1/092_U_235)*:
```
                                                                     1 0  0  0
 9.223500+4 2.330248+2          1          1          0          79228 1451    1
 0.000000+0 1.000000+0          0          0          0          69228 1451    2
 1.000000+0 2.000000+7          0          0         10          79228 1451    3
 0.000000+0 0.000000+0          0          0        733        1249228 1451    4
```
After adding the missing 0 to the end of the first line from the file at the original example linked location, the file loaded without a problem. 

I don't know whether this is a problem with the files in the web database or something the endf-reader should be robust against, but perhaps it would be sensible to link to a static, specific version of the data file that the reader supports. While this may not ensure the most up-to-date data (the location for more current sources could be suggested), it would ensure that the example will always work, and provides a reference file for comparison in the future.

### PR DESCRIPTION
**Pull request by mehmeturkmen**
This PR resolves the issue #1226. I have changed only the ENDF links causing library reading error. From ENDF/B-VII.0 to ENDF/B-VII.1.

### CODE REVIEW

**Review by opotowsky — COMMENTED** [review]
Since urlretrieve is deprecated, would you mind updating it to the following?: https://github.com/pyne/pyne/issues/1276#issuecomment-673735565

**Comment by ngranda** [comment]
> Since urlretrieve is deprecated, would you mind updating it to the following?: [#1276 (comment)](https://github.com/pyne/pyne/issues/1276#issuecomment-673735565)

I've made a pull request to @mehmeturkmen's repo that removes urllib

**Comment by mehmeturkmen** [comment]
> > Since urlretrieve is deprecated, would you mind updating it to the following?: [#1276 (comment)](https://github.com/pyne/pyne/issues/1276#issuecomment-673735565)
> 
> I've made a pull request to @mehmeturkmen's repo that removes urllib

@ngranda I have updated the example based on your suggestion. So I will not merge  your PR.

**Comment by opotowsky** [comment]
Haha, I realized this PR is the example and what I PRed is the tutorial documentation, but it still needs to go in either way. Thanks for merging the PR!

**Comment by opotowsky** [comment]
@mehmeturkmen The nosetests3 failure makes me think you haven't rebased this in a bit? Is that true?

**Comment by mehmeturkmen** [comment]
> Haha, I realized this PR is the example and what I PRed is the tutorial documentation, but it still needs to go in either way. Thanks for merging the PR!

Yeah I figured out. No problem.

**Comment by mehmeturkmen** [comment]
> @mehmeturkmen The nosetests3 failure makes me think you haven't rebased this in a bit? Is that true?

Well, I remember I did but maybe not!. How can I check that?

**Comment by opotowsky** [comment]
> > @mehmeturkmen The nosetests3 failure makes me think you haven't rebased this in a bit? Is that true?
> 
> Well, I remember I did but maybe not!. How can I check that?

on your branch locally run `git rebase upstream/0.7.0-rc`
be prepared for merge conflicts..... (if not, take a moment of silence to appreciate simplicity)

**Comment by opotowsky** [comment]
> > > @mehmeturkmen The nosetests3 failure makes me think you haven't rebased this in a bit? Is that true?
> > 
> > 
> > Well, I remember I did but maybe not!. How can I check that?
> 
> on your branch locally run `git rebase upstream/0.7.0-rc`
> be prepared for merge conflicts..... (if not, take a moment of silence to appreciate simplicity)

Oh yea and you 'll wanna force push when the rebase is successful: `git push -f mehmeturkmen endf-reader`

**Comment by mehmeturkmen** [comment]
> > > > @mehmeturkmen The nosetests3 failure makes me think you haven't rebased this in a bit? Is that true?
> > > 
> > > 
> > > Well, I remember I did but maybe not!. How can I check that?
> > 
> > 
> > on your branch locally run `git rebase upstream/0.7.0-rc`
> > be prepared for merge conflicts..... (if not, take a moment of silence to appreciate simplicity)
> 
> Oh yea and you 'll wanna force push when the rebase is successful: `git push -f mehmeturkmen endf-reader`

Ok. I rebased it with no conflicts. It seems nothing changed. Still there are unsuccessful checks.

**Comment by opotowsky** [comment]
so did the force push work?

**Comment by opotowsky** [comment]
> so did the force push work?

Because this branch isn't up to date (I pulled it, rebased, pushed to my own repo, and compared it against yours and the history is definitely different.)

**Comment by mehmeturkmen** [comment]
I think I rebased a different branch of repository, namely 0.7.0-rc. Sorry, It is my fault. I am working on end-reader branch right now!

**Comment by opotowsky** [comment]
> I think I rebased a different branch of repository, namely 0.7.0-rc. Sorry, It is my fault. I am working on end-reader branch right now!

Ah ok! that would do it. Let me know if you need any git clarification/help.

**Comment by mehmeturkmen** [comment]
> > I think I rebased a different branch of repository, namely 0.7.0-rc. Sorry, It is my fault. I am working on end-reader branch right now!
> 
> Ah ok! that would do it. Let me know if you need any git clarification/help.

I rebased enf-reader branch. But, we still have got at least one fail, changelog_update. How can we resolve it?

**Comment by opotowsky** [comment]
First the easy part: 
CHANGELOG.rst is in the main directory of pyne, and you just add an entry into it. The section you'll want to add this to is "fixes in examples and tutorials"

**Comment by opotowsky** [comment]
Well actually all may be well. Do that, and push it, and lets see what happens

**Comment by mehmeturkmen** [comment]
> Well actually all may be well. Do that, and push it, and lets see what happens

I think this time we are ok:)

**Pull request merged**
