### PR TITLE
(Docker) Install all Python packages with Pip

### PR DESCRIPTION
**Pull request by epassaro**
Following https://github.com/pyne/pyne/issues/1144.

### CODE REVIEW

**Comment by bam241** [comment]
looks good to me, just an update of the changeling is missing
Have you try to build a docker image with this ?

**Comment by epassaro** [comment]
I do not have so much experience with Docker. I made an image using the DockerHub web interface using the dockerfile from my fork: https://hub.docker.com/r/epassaro/pyne.

Also I should modify the changelog manually?

**Comment by opotowsky** [comment]
Yep you modify the changelog manually!

**Comment by gonuke** [comment]
Either @bam241 or I can test your dockerfile, but it looks like the one on Dockerhub used the old file: https://hub.docker.com/r/epassaro/pyne/dockerfile

**Comment by gonuke** [comment]
Oops - I was wrong - it is using a new Dockerfile!

**Comment by gonuke** [comment]
It looks like when we pip install `nose` with python3, the executable is not called `nosetests3`.  So this breaks `travis-run-tests.sh` and we can't quite run tests with the current CI setup.  @bam241  - we should discuss the remedy to this....

**Comment by bam241** [comment]
Have you tried the image @epassaro linked ? this image is built with python2.7.  so their will be no `nosetests3` in it

have you tried it on an other docker image ?

**Comment by bam241** [comment]
I have the same issue on Mac, nose tests installed through pip come as nosetests-3.x not nosetests3...

**Comment by bam241** [comment]
I am note sure that the travis_tests.sh is really useful... it basically only run the nosetests....

**Comment by bam241** [comment]
working ! thx @epassaro for all the work.

Merging !

**Pull request merged**
