### PR TITLE
Update tutorial to be yt 3.x compliant

### PR DESCRIPTION
**Pull request by crbates**
and other fixes. #662 re-opened.

### CODE REVIEW

**Comment by crbates** [comment]
the diffusion notebook now runs without any yt errors but JSanimation no longer seems to work properly with recent ipython versions.

**Comment by scopatz** [comment]
I think that is OK.  Maybe we should drop JSanimation. I was a neat trick, but non-essential.

**Comment by scopatz** [comment]
Also pymovie seems much better

**Comment by crbates** [comment]
@scopatz I propose we merge this after adding a warning at the start of the 8th tutorial that links to the issue because I don't think obscure yt/mesh problems should block 0.5.

**Comment by scopatz** [comment]
I completely agree.

**Comment by scopatz** [comment]
We are going to need to sit down with some of the yt folks to really hammer this out.

**Comment by crbates** [comment]
ping @scopatz

**Comment by scopatz** [comment]
This looks about as good as it is going to get.  Thanks for all the hard work @crbates!

**Pull request merged**
