### PR TITLE
removed extern C from source sampling

### PR DESCRIPTION
**Pull request by scopatz**
CC @ljacobson64 @makeclean @FlanFlanagan May address #919

### CODE REVIEW

**Comment by scopatz** [comment]
OK this passes test on linux, but testing on Mac with clang would be highly desirable.

**Comment by makeclean** [comment]
IIRC we need that when linking those routines into a fortran based code - eg MCNP

**Comment by scopatz** [comment]
Hmm, well this should have never worked for that :).  This is clearly C++ code, not C code meant for interacting with fortran.  I think another interface layer is needed, if MCNP linkage is needed.

**Comment by scopatz** [comment]
Also, are you all still experiencing issues on Mac?

**Comment by gonuke** [comment]
Hmm... yes - I think these extern's should be in the `cpp` file... not the `hpp` file - and only around certain functions...

**Comment by gonuke** [comment]
hmmm 2.0 ... no - it should be in the hpp, but perhaps more localized to only the functions that will be in the interface for C/FORTRAN

**Comment by scopatz** [comment]
2.0 makes sense to me

**Comment by scopatz** [comment]
If someone wants to put in an alternative fix, that would be awesome!

**Comment by gonuke** [comment]
Perhaps @zxkjack123 can take a look at this since he is working in this part of the code anyway.

It would be useful to add a small FORTRAN test - a short F90 file that calls each of the methods in the interface to demonstrate that they are, in fact, callable.

**Comment by elliottbiondo** [comment]
@gonuke see:

http://pyne.io/usersguide/source_sampling.html#fortran-interface

**Comment by elliottbiondo** [comment]
I can't speak to whether the "extern C" is necessary but I will say that the version of this file prior to this PR did work from Fortran and MCNP without any additional interface layer :)

**Comment by gonuke** [comment]
Not sure I understand exactly what you mean by your comment @elliottbiondo .... 

I don't think we need any additional layer, but that we can/should more carefully localize where the `extern C`.  

Most importantly, I think we need a test for this interface to make sure it doesn't get broken by proposed changes like this.

**Comment by gonuke** [comment]
... and you have pointed us to a good test in the documentation

**Comment by gonuke** [comment]
Uggh.. but we have no infrastructure for tests that required compiled code...

**Comment by elliottbiondo** [comment]
My interface comment was in response to something way earlier in this thread. Not important.

**Comment by gonuke** [comment]
Various users have successfully used this without this change.  The methods are called directly from FORTRAN90, for example, within MCNP and require these delimiters to make the methods available across this language interface.

**Pull request closed without merging**
