### PR TITLE
User std::abs

### LINKED ISSUE #792: abs used where std::abs seems more appropriate
`abs` implicitly casts its arguments to integers. This produces two compile warnings when building pyne.

### PR DESCRIPTION
**Pull request by dschwen**
Small compile warning fix.

Closes #792

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks a ton for putting this in @dschwen.  It seems that there is an unrelated bug in that is causing the CI to fail. Can you pull in my fix from my  `s32cf` branch, please? Thanks!

**Comment by dschwen** [comment]
Will do in about an hour.

**Comment by dschwen** [comment]
Hmm, yeah, no surprise here, as #794 failed as well :-)

**Comment by scopatz** [comment]
Ok #794 now works, can you remerge please, @dschwen?

**Comment by dschwen** [comment]
@scopatz this seems to make a test diff. Could you have a look if this is a sensible change after all?

**Comment by scopatz** [comment]
These are probably legitimate changes in the underlying data file @dschwen.  Feel free to update the tests.  Thanks!

**Comment by dschwen** [comment]
Finally!

**Comment by scopatz** [comment]
Woohoo! Thanks for bearing with us.

**Pull request merged**
