### PR TITLE
Changed the tag naming convention for MeshTally creation to be more cons...

### PR DESCRIPTION
**Pull request by Pshriwise**
...istent with the error suffix used in the mesh operator. Also updated said error suffix to be more accurate about what is contained in that tag value.

### CODE REVIEW

**Comment by scopatz** [comment]
This looks reasonable to me, but someone more familiar with the mesh stuff should probably also review (@elliottbiondo @makeclean or @kkiesling)

**Comment by Pshriwise** [comment]
Taking a look at the failing tests in CI now...

**Comment by scopatz** [comment]
Oh, those aren't your fault.  One is @kkiesling's and the other is this weird bins issue that happens randomly that we should try to fix.  I can't reproduce that on my machine, though @elliottbiondo has in the past.

**Comment by Pshriwise** [comment]
Ahhh ok I remember that from my PR to the sandbox.

**Comment by elliottbiondo** [comment]
We aren't getting any meaningful info out of CI because of the test_bins.py issue and Travis seems to give up upon receiving the first failure.

I would not be surprised if this PR breaks something in R2S though, so either CI or old-school CI (manually clone PR branch, build, run tests) needs to be done.

**Comment by scopatz** [comment]
> We aren't getting any meaningful info out of CI because of the test_bins.py issue

It seems to fail randomly on CI too.  https://travis-ci.org/pyne/pyne/builds/56724604 did not fail with the bins issue, it failed later because of fluka.  Also note that this seems to be a Python 2 only issue.

> Travis seems to give up upon receiving the first failure.

Yeah, I designed it that way because otherwise Travis would report success, and I didn't want to think about the bash logic for running all of the test but it one failed, report an error.  Also, there are many nose runs because loading in many moab files was causing memory errors on Travis, which is pretty memory constrained.

**Comment by Pshriwise** [comment]
Yeah I'm actually getting some broken tests locally now. The tests are still expecting the old error suffix it looks like. Is there a particular procedure for changing something like that in PyNE.

**Comment by elliottbiondo** [comment]
>The tests are still expecting the old error suffix it looks like. Is there a particular procedure for changing something like that in PyNE.

How many tests are we talkin'?

@scopatz I took a look at test_bins.py  and bins.py. As I said in the Hangout today, I recall times where test_bins has failed due to array values being reversed. Likewise, it looks like a lot of reversing is going on in both test_bins.py and bins.py. I am how any single operation would yield non-deterministic behavior. In any case, the current test_bins.py does not seem to be a simple reversal:

(mismatch 100.0%)
 x: array([ 0.375])
 y: array([  4.248662e+27])

I think this is something that is going to require your expertise (I believe you wrote bins.py?)?

**Comment by Pshriwise** [comment]
I'm seeing 4 tests failing. All related to mesh operators.

test_add_statmesh
test_divide_statmesh
test_multply_statmesh
test_subtract_statmesh

All with this error.
TagNotFoundError: iMesh_getTagHandle: problem getting handle for tag named 'flux_error_rel_error'  (MOAB Error Code: MB_TAG_NOT_FOUND)

Because the error suffix has changed.

**Comment by elliottbiondo** [comment]
Those unit tests live in ```tests/test_mesh.py```. You should update the tag names to the correct convention there.

**Comment by Pshriwise** [comment]
Kk will do. Any other documentation to go with changing a test file?

**Comment by scopatz** [comment]
OK, this bins thing is almost certainly a floating point arithmetic issue.

**Comment by elliottbiondo** [comment]
> Any other documentation to go with changing a test file?

No I do not think any is necessary for this case.

**Comment by elliottbiondo** [comment]
(PR closed erroneously by me -- reopened)

**Comment by scopatz** [comment]
I HAVE FOUND THE BUG!

**Comment by Pshriwise** [comment]
Haha nice work @scopatz. Should I wait on the [bin PR](https://github.com/pyne/pyne/pull/713) to go in and add those changes?

Everything is passing now on my machine but someone should probably pull this branch and double-check, yes?

**Comment by scopatz** [comment]
Probably, though I think we can relaunch the job once the bins one is in.

**Comment by scopatz** [comment]
Unlike polyphemus, batlab does a merge when before running the tests.

**Comment by scopatz** [comment]
Relaunching.

**Comment by scopatz** [comment]
Thanks @Pshriwise!  Looks like everything is passing.  I would still feel more comfortable if someone more familiar with  mesh merged this...

**Comment by elliottbiondo** [comment]
This is good. Merged.

**Comment by elliottbiondo** [comment]
Thanks @Pshriwise!

**Pull request merged**
