### PR TITLE
adding manual trigger for docker building workflow

### PR DESCRIPTION
**Pull request by bam241**
adds a manual trigger to build docker CI img

### CODE REVIEW

**Comment by gonuke** [comment]
rebase this to get your recent changelog update and skip the build/test

**Comment by bam241** [comment]
we need to ignore changelog entry as well !

**Comment by bam241** [comment]
we have circled the full loop, adding `changelog` as ignore path to `build_test.yml` this PR will trigger `build_test.yml` :)

**Comment by gonuke** [comment]
.... and now we need to rebase the CHANGELOG :)

**Pull request merged**
