### PR TITLE
positive ensdf nuc ids in gamma x-rays

### LINKED ISSUE #1020: data.gamma_xrays runtime error
Hi, this is Andreas Vogt.
When calling 
In [8]: data.gamma_xrays(892270000)
I get the following runtime error: 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-4e8f7ba066c4> in <module>()
----> 1 data.gamma_xrays(892270000)
data.pyx in pyne.data.gamma_xrays()
RuntimeError: P��

Other nuclei work just fine, e.g.
In [8]: data.gamma_xrays(902320000)
Out[8]:
[(88.47, 0.002807402708729183),
 (85.43, 0.001718691938284006),
 (100.0, 0.001308041352986811),
 (12.3, 7.139185247404002)]

Is this a matter of the h5 table? I checked that data.gamma_xrays works at least for all even-mass nuclei along the 232Th and 238U decay chains.

Best regards!

### PR DESCRIPTION
**Pull request by scopatz**
should fix #1020 

CC @FlanFlanagan @pyne/core

### CODE REVIEW

**Comment by gonuke** [comment]
Do we know if the use of negative numbers means anything in ENSDF?

**Comment by scopatz** [comment]
The negative numbers didn't come from ENSDF itself.  Rather they were an artifact of computing level differences, and came soley from PyNE :frowning_face: ENSDF represents nuclides in AAALL form

**Comment by gonuke** [comment]
Shouldn't we take the abs value of `daughter_id` as soon as we set it then? e.g. line 668?

**Comment by scopatz** [comment]
Yeah, good point

**Comment by scopatz** [comment]
updated!

**Comment by gonuke** [comment]
(Feeling like a pest but...)  also for the others? `gp2`, `gparent`, `gdaughter`? 

 or should `_to_id()` be fixed... or `nucname.ensdf_to_id()` called by `_to_id()`?

I don't understand any of this data well enough to know where the right place to fix it is, but taking the `abs()` so far downstream seems like something that will bite us in the future

**Comment by scopatz** [comment]
I think `_to_id()` and `ensdf_to_id()` are actually always producing positive numbers. The problem is with `id_from_level()` and some of the levels being wrong.

**Comment by scopatz** [comment]
Yeah, just checked and id_from_level() produces negative number for some specific reason I don't understand.  But they don't seem relevant to us here.  Just `abs()`'d all call sites in this function.

**Comment by gonuke** [comment]
As far as I can tell, `id_from_level()` returns a negative number if it does not find an energy level close to the requested `level`, where currently the definition of close is "3.0" - for some poorly documented reason in some undocumented units...

I agree that we can ignore the negative here, but I can only assume that one is supposed to check the sign and act on it, while also taking the abs() of that result.

I'll merge this, but I can't say that I like it...  unless you think it's worth a deeper look

**Comment by scopatz** [comment]
Yeah, I am not sure that I like it either, but it does fix the problem in the short to medium term

**Comment by gonuke** [comment]
Merging this because it does address #1020, even though the author and reviewer agree that it may not be the best solution.  Created #1023 to capture this for the future.

**Comment by gonuke** [comment]
Thanks @scopatz

**Pull request merged**
