### PR TITLE
Fixes the Serpent2 depletion file issue

### PR DESCRIPTION
**Pull request by andrewryh**
I have added function wich seek and remove an abundant Serpent2 block of code in *_dep.m file.
The solution was tested on different output files including Serpent 2 example "PWR Burnup Calculation Based on NEA Benchmark"

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @andrewryh - Thanks for putting this in!  It seems like there is failing test related to serpent: https://travis-ci.org/pyne/pyne/builds/235837834#L3001  Would you mind taking a look? Thanks!

**Comment by andrewryh** [comment]
Hello @scopatz, I gonna fix it. Very strange, it passed all test on my local machine.

**Comment by scopatz** [comment]
Odd, well, you can keep pushing up to this branch to rerun the CI.  Also Circle let's you SSH into the container for 30 min if you need to use that too.

**Comment by andrewryh** [comment]
@scopatz Looks fine for me now

**Comment by scopatz** [comment]
Thanks a ton @andrewryh!

**Pull request merged**
