### PR TITLE
Clarifies main documentation index.

### LINKED ISSUE #727: fortran api is missing
The C++ and Fortran API only has C++: http://pyne.io/cppapi/index.html. Is that on purpose? I know we wanted to document how to wrap fortran code, we need to sort this out and clarify.

### PR DESCRIPTION
**Pull request by nathanb01**
This PR should resolve #727.

Since there isn't a Fortran API for the user, there should probably not be a link under "Using PyNE" that says Fortran API Documentation. The [Fortran API Documentation](https://github.com/pyne/pyne/blob/develop/docs/devsguide/fortran.rst), which discusses f2py and fortran wrappers, resides in the devsguide.

### CODE REVIEW

**Comment by zxkjack123** [comment]
Could you please add a news file for this PR? For example, the `news/speed_up_r2s_step2_2.rst` at https://github.com/pyne/pyne/pull/1134/files#diff-e6c3d2c346decbb8821a44781d0a4465.

**Comment by gonuke** [comment]
@nathanb01 - I'll be happy to merge this once you have added a news file

**Comment by nathanb01** [comment]
Sorry I disappeared for about a month, here is that news file.

**Comment by gonuke** [comment]
thanks @nathanb01

**Comment by gonuke** [comment]
I just merged this from the website, but it didn't close the PR - it might be related to firewall issues on my end???

**Comment by zxkjack123** [comment]
@gonuke No, it shows `This branch has conflicts that must be resolved` on my end.

**Comment by gonuke** [comment]
The reason for the conflict, though, is that these changes are now merged in commit a65303c2b381234d824e42ee79483394a2207672 attributed to me

**Comment by gonuke** [comment]
I don't know how we got into this state, but the changes are correctly attributed to @nathanb01. 

I think the only option will be to close this PR.

**Comment by zxkjack123** [comment]
I checked the commit log of the current develop branch:
```
git log
commit a65303c2b381234d824e42ee79483394a2207672 (HEAD -> develop, upstream/develop, origin/develop, origin/HEAD)
Merge: 8f0fcd78 a8b2a50e
Author: Paul Wilson <paul.wilson@wisc.edu>
Date:   Wed Jul 31 08:22:17 2019 -0500

    Merge pull request #1149 from nathanb01/Issue727
    
    Clarifies main documentation index.
```
It shows that this PR has been merged into `upstream/develop`. Agree to close this PR.

**Pull request closed without merging**
