### PR TITLE
More Build fixes

### LINKED ISSUE #983: ZeroDivisionError happened when nuc_data_make
Python version: 2.7
Error information:
```
Traceback (most recent call last):
  File "./scripts/nuc_data_make", line 6, in <module>
    main()
  File "/home/zxk/.local/lib/python2.7/site-packages/pyne/dbgen/nuc_data_make.py", line 157, in main
    make_map[mo](args)
  File "/home/zxk/.local/lib/python2.7/site-packages/pyne/dbgen/decay.py", line 472, in make_decay
    make_decay_half_life_table(nuc_data, build_dir)
  File "/home/zxk/.local/lib/python2.7/site-packages/pyne/dbgen/decay.py", line 380, in make_decay_half_life_table
    level_list = parse_level_data(build_dir)
  File "/home/zxk/.local/lib/python2.7/site-packages/pyne/dbgen/decay.py", line 252, in parse_level_data
    level_list = ensdf.levels(f, level_list)
  File "/home/zxk/.local/lib/python2.7/site-packages/pyne/ensdf.py", line 1008, in levels
    _parse_level_record(level_l)
  File "/home/zxk/.local/lib/python2.7/site-packages/pyne/ensdf.py", line 226, in _parse_level_record
    tfinal, tfinalerr = _to_time(l_rec.group(5), l_rec.group(6))
  File "/home/zxk/.local/lib/python2.7/site-packages/pyne/ensdf.py", line 137, in _to_time
    tfinal, tfinalerr = _halflife_to_seconds(value, err, t_unit)
  File "/home/zxk/.local/lib/python2.7/site-packages/pyne/ensdf.py", line 118, in _halflife_to_seconds
    sec_err = (scale / (value - minus) - sec_time,
ZeroDivisionError: float division by zero
```

### PR DESCRIPTION
**Pull request by scopatz**
This enables pyne to build and test from a clean build and specifically fixes `nuc_data_make` This should allow us to issue another minor release and update the conda packages.  Should fix #983

### CODE REVIEW

**Comment by scopatz** [comment]
CC @FlanFlanagan  @zxkjack123 @gonuke @makeclean @katyhuff @kkiesling

**Comment by kkiesling** [comment]
Yep, this looks to have fixed the scripts/nuc_data_make issue. Just wondering (as I am unfamiliar with the data), if we have a local copy already of mednew.dat, why bother to try download it at all? Why not just always use the local copy?

**Comment by FlanFlanagan** [comment]
Looks good to me.

**Comment by zxkjack123** [comment]
Looks good to me.

**Pull request merged**
