### PR TITLE
Rewrite and expansion of pyne.endf.Evaluation

### PR DESCRIPTION
**Pull request by paulromano**
This pull request implements a major reworking of the functionality in the pyne.endf.Evaluation class. For starters, the class has been expanded such that it supports parsing ENDF data in all files with MT < 30, i.e. everything other than covariance files. I've tried to make the functionality and documentation a little more user-friendly (although I still need to add more docs before this PR can be considered complete). To highlight some of the salient changes:
- Got rid of the ENDFFile\* and ENDF*Record classes
- Reworked Tab1 class to be much more useful. The class now has a `__call__` method that accepts scalar or array x and returns back interpolated y value(s). 
- Use polymorphism judiciously. For example, in ENDF, fission nu can be stored either as polynomial coefficients or as a tabulated function. In my implementation, it's stored either as numpy.polynomial.polymial.Polynomial or Tab1. Since both can be called as functions, to a user it doesn't matter what the actual type is. Angular distributions also take advantage of polymorphism with numpy.polynomial.legendre.Legendre and Tab1.
- Added energy distribution classes. The idea is that the functionality could be expanded in the future, e.g. each energy distribution could have a sample() method or integrate() method.
- Added resonance energy range classes. I'm hoping to implement resonance reconstruction in the future as a reconstruct() method to these classes.

There are a few things I need to do before this PR is complete:
- [x] Add tests for Evaluation and related classes
- [x] Add IPython notebook demonstrating capabilities
- [x] Add documentation to user's guide

Nevertheless, I thought it would be good to initiate this to start getting reviewer feedback.

### CODE REVIEW

**Comment by scopatz** [comment]
@paulromano - it looks like this fails on Python 3, somewhere.

**Comment by scopatz** [comment]
Sorry for taking so long to review this and fix CI.

**Comment by scopatz** [comment]
Also, annoyingly, github isn't rendering the diff because it is too long :(

**Comment by scopatz** [comment]
Dang, I can't comment inline....

**Comment by scopatz** [comment]
`radiation_type()` needs a docstring or to be private.

**Comment by scopatz** [comment]
`EndfTape` should probably not inherit directly from `file`.  It is better to inherit from the ABCs in the `io` module.  Probably `io.RawIOBase` see https://docs.python.org/3/library/io.html#class-hierarchy

**Comment by scopatz** [comment]
Not relevant if you move to RawIOBase, but the init of EndfTape should use super, rather than calling superclass methods directly.

``` diff
  def __init__(self, *args, **kwargs):
-     file.__init__(self, *args, **kwargs)
+     super(EndfTape, self).__init__(self, *args, **kwargs)
```

**Comment by scopatz** [comment]
The variable `itemList` is camel cased.  Should be `item_list`, or even better just `items`

**Comment by scopatz** [comment]
`AngularDistribution` has a no-op init.  This should be removed in favor of pass.

``` diff
  class AngularDistribution(object):
-     def __init__(self):
-        pass
+     pass
```

**Comment by scopatz** [comment]
PEP8: `Reaction` takes an `MT` parameter on init.  This should be renamed `mt`

**Comment by scopatz** [comment]
Same as `AngularDistribution` but for `AdlerResonance`

**Comment by scopatz** [comment]
Overall, this looks very good.  I am a little surprised that their are no new tests here or changes to existing tests.  It definitely seems like some of the interfaces have changed... maybe they weren't tested before?

In any event, let us know when this is ready for another look!  Thanks a ton @paulromano!

**Comment by paulromano** [comment]
@scopatz This should be ready for another look. I got around the file-inheritance issue by just getting rid of the EndfTape class and instead making its three methods normal functions. All the other trivial comments are addressed as well. I added five new tests to test_endf.py that check a variety of data from ENDF neutron, photoatomic, electroatomic, decay, and atomic relaxation sublibraries. It certainly doesn't test every piece of data, but it should be enough to catch any major changes to the API.

**Comment by scopatz** [comment]
Thanks @paulromano!  Great work, as always.

**Pull request merged**
