### PR TITLE
fixed fluka tests

### PR DESCRIPTION
**Pull request by kkiesling**
Fixed the assert_equal and import errors in test_fluka.py. Also added the file it writes out to the the .gitignore.

### CODE REVIEW

**Comment by scopatz** [comment]
Looks reasonable to me :) Waiting for CI.

**Comment by scopatz** [comment]
This needed a relaunch.

**Comment by kkiesling** [comment]
It looks like this is failing with that MOAB ERROR thing now in test_dagmc.py. It doesn't look like there are any fails or errors with the tests though, but the script still fails on test_dagmc.py..

**Comment by kkiesling** [comment]
If this is getting hung up on the fact that the entire test_dagmc.py file is on separate processes, this may or may not be fixed with pr #712 ...

**Comment by scopatz** [comment]
Now that #712 is in, you probably should update this branch @kkiesling. Thanks!

**Comment by kkiesling** [comment]
Looks like it's just those same two tests that have been causing trouble now from test_bins

**Comment by scopatz** [comment]
Looks great!  Thanks!

**Pull request merged**
