### PR TITLE
Fix ENDF parsing of TSL files using SCT for non-principal atoms

### PR DESCRIPTION
**Pull request by tkittel**
Opening pull request as request on issue #1209 .

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks for this contribution @tkittel !  Are you able to add a test for this? Ideally a case that would have failed without this addition.

**Comment by tkittel** [comment]
I don't really have a test case - apart from the SiO2 and benzene files from ENDF8. I don't think I am allowed to just commit those. If you have access to the relevant files on some hidden test server, it should be simple to simply try to parse those files.

**Comment by gonuke** [comment]
Hmmm.... that is a problem.  Some of our tests download the files they will use from the internet, but these seem to only be available as part of larger zip/tarballs, which is not suitable for testing.

I guess the only other option would be to construct a minimally sufficient file that includes the features in question, but that sounds like too much work!

**Comment by tkittel** [comment]
Yeah, I definitely don't have the skills to start learning how to construct ENDF files. I barely know how to read them, which is why I turned to PyNE in the first place :-)

**Comment by gonuke** [comment]
Ha!  I don't really want to do that either.

**Pull request merged**
