### PR TITLE
Same PR as #767

### PR DESCRIPTION
**Pull request by elliottbiondo**
This is the same PR as #767, but I messed some stuff up by pushing to the wrong remote (I have fully resolved this issue).

### CODE REVIEW

**Comment by elliottbiondo** [comment]
@scopatz I made the changes in #760 but now some AHOT unit tests fail. Unless I am misunderstanding how Fortran continue lines work I think I may have found some deeper issues...

**Comment by scopatz** [comment]
Don't line continuations require a trailing backslash?

**Comment by scopatz** [comment]
Maybe @crbates can weigh in.

**Comment by crbates** [comment]
So I think this is just an integral tests != correctness tests issue. We 'luckily' had a situation where the fortran 90 cutoff of 132 characters left us with all valid variables names and statements. I think the best we can do is to update the tests to match the new outputs and open an issue to check ahot for correctness.

**Pull request merged**
