### PR TITLE
DagMC Py3k fix

### PR DESCRIPTION
**Pull request by scopatz**
This is an emergency patch for DagMC on Python 3.

### CODE REVIEW

**Comment by crbates** [comment]
can you pull against develop or run this on CI manually?

**Comment by crbates** [comment]
nvm it looks like it's gorgus is down

**Comment by crbates** [comment]
so I need to add `/lib` to `${MOAB_LIBRARY_DIRS}`  here https://github.com/crbates/pyne/blob/develop/CMakeLists.txt#L109 to get this to compile properly for me on mac

**Comment by crbates** [comment]
with python 3 that is

**Comment by scopatz** [comment]
Could you please PR that change into my fork!  Thanks!

**Comment by scopatz** [comment]
This passes CI!

**Comment by scopatz** [comment]
ping!

**Comment by elliottbiondo** [comment]
Looks good. Merged.

**Pull request merged**
