### PR TITLE
Data theory

### PR DESCRIPTION
**Pull request by crbates**

### CODE REVIEW

**Comment by scopatz** [comment]
This could use a TOC entry in the index.rst

**Comment by scopatz** [comment]
Was this supposed to be closed?

**Comment by kkiesling** [comment]
Oh crap. I think I closed the wrong one.. mis-click..  No.. my apologies. Reopened.

**Comment by kkiesling** [comment]
Actually.. it says I can't reopen..

**Comment by kkiesling** [comment]
Oh wait.. I don't think this ever got merged into the version release branch before we deleted it so it closed it automatically. Can this stuff just go into master if it was for the release instead?

**Comment by scopatz** [comment]
Yes, probably  Would you mind doing that?

**Comment by kkiesling** [comment]
Okay so I am a little scared to do this without checking the process first.. I merged Cameron's data_theory branch to my master branch and pushed to my own master. Now can I just push directly to the upstream master now? Or do I need to do something else first?

**Comment by scopatz** [comment]
Yes, please do.  And then merge master into develop and push to origin and upstream

**Comment by kkiesling** [comment]
Done.

**Comment by scopatz** [comment]
u = "the best"

**Pull request closed without merging**
