### PR TITLE
Changes for release 0.7.8

### PR DESCRIPTION
**Pull request by gonuke**
This contains version number changes for a micro-/patch-level release.

By issuing this release, we can return to getting conda-forge working again and try to be more regular with releases.

### CODE REVIEW

**Comment by ahnaf-tahmid-chowdhury** [comment]
While developing NukeLab, I have noticed the following deprecation warning:
>DEPRECATION: Loading egg at /opt/conda/lib/python3.11/site-packages/pyne-0.7.7-py3.11.egg is deprecated. pip 23.3 will enforce this behavior change. A possible replacement is to use pip for package installation.

I believe we should transition to using pip for package installation instead of relying on setup.py.

My PR is fully functional for Linux builds. Should I proceed with completing the task before we release a new version of PyNE?

**Comment by gonuke** [comment]
Do you have a minimal PR that only addresses this issue?  Or are you referring to the SciKit-Bld PR? I am interested in moving this release along rapidly and worry that reviewing PR #1500 will take some time

**Comment by ahnaf-tahmid-chowdhury** [comment]
In that case, we should contemplate releasing v0.7.8 first. Following that, we can transition to the Scikit-Build approach and prepare for a significant release, v0.8.0.

**Review by ahnaf-tahmid-chowdhury — APPROVED** [review]
It seems everything is OK. Once I've resolved the Windows build issue in my pull request, we can schedule a meeting to discuss Scikit-Build.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Is there anything else that needs to be addressed? If everything is satisfactory from your perspective, I'm ready to proceed with merging this.

**Comment by gonuke** [comment]
I think this may be ready, but merging DAGMC/PyNE requires some synchronization - perhaps we can manage it on Thursday's call?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Sure

**Comment by ahnaf-tahmid-chowdhury** [comment]
I am considering adding Read the Docs support to the PyNE doc before releasing the next version. This feature would provide a version history for each PyNE release from the current one onwards. However, the current `setup.py` is complex, making it unsuitable for use in the Read the Docs build process. As an alternative, we can use the conda version of PyNE for this purpose. Should we proceed with this addition for the upcoming PyNE release or would it be better to postpone it for a later release?

**Comment by gonuke** [comment]
I worry that Read the Docs is another big change that will delay release.  Ideally, with enough energy, we can become well-practiced at issuing releases and do it often.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think since Geant4 is fixed, we can now start releasing this. It would be better if we first create the pip version of PyNE and then start working on Read the Docs.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think we are ready for this release?

**Comment by gonuke** [comment]
I've launched the test to build the CI docker image based on the newer stable version of DAGMC here: https://github.com/pyne/pyne/actions/runs/7309945240

**Comment by gonuke** [comment]
These builds were successful, so I think this is ready to merge for release

**Pull request merged**
