### PR TITLE
Redesign Build System for PyNE with Scikit-Build

### LINKED ISSUE #1250: Add features to conda-forge support
Currently, the following features/dependencies are not available in the conda-forge version of PyNE:

* [x] AHOT (#1305)
* [x] pymoab (#52 in feedstock)
* dagmc (requires upstream work on conda-forge/dagmc-feedstock)
* [ ] openmc (#54 in feesdstock)

(please add others as they are identified)

### LINKED ISSUE #1372: Python 3.8 support on macOS
Hi! The `conda-forge` package of `pyne` requires macOS <=3.7. Do you have any plans to make it work with 3.8 in the short term?

Thanks.

### LINKED ISSUE #1380: Create pip installable package
Although we already have a reasonably stable condo build, many users are interested in a package that can be installed by `pip`.

Some tips on how todo this: https://thomastrapp.com/blog/building-a-pypi-package-for-a-modern-cpp-project/

See also `conda-press` although it may no longer be supported.

### LINKED ISSUE #1442: Build system update
**Is your feature request related to an enhancement?

Improved installation experience for users, updated build tools

**Describe the solution or outcome you'd like.**<br/>
I had a look into the setup.py which I believe takes the best possible  approach to building C++ / Python projects when it was designed. Like other build related packages of the same era implemented distutils/setuptools functions are used. This was the only available option as there was no public API for implementing a package builder.

The Python build tools have been evolving in the meantime and might be ready to provide a simpler solution to building C++/ Python projects.
[PEP 517](https://www.python.org/dev/peps/pep-0517) by standardizing the interface for package builders
[PEP 518](https://www.python.org/dev/peps/pep-0518) which allowed users to specify the exact build requirements for their package.

We could look at [scikit-build](https://github.com/scikit-build/scikit-build) which has some nice [minimal examples](https://scikit-build.readthedocs.io/en/latest/usage.html#basic-usage-example) on their docs

"scikit-build is an improved build system generator for CPython C/C++/Fortran/Cython extensions. It provides better support for additional compilers, build systems, cross compilation, and locating dependencies and their associated build requirements."

I can look into this topic a bit more but just wanted to raise the issue in case anyone else is looking into updating the build system?

**Describe alternatives you've considered.**<br/>

https://github.com/FFY00/trampolim
https://github.com/python-poetry/poetry

**Additional Context**<br/>
pypi is also supported
https://scikit-build.readthedocs.io/en/latest/make_a_release.html#pypi-step-by-step
Conda is also supported
https://scikit-build.readthedocs.io/en/latest/make_a_release.html#conda-step-by-step

There is a mailing support group for the build system https://groups.google.com/forum/#!forum/scikit-build

### LINKED ISSUE #1483: pyne install with conda
**Describe the Bug**<br/>

**To Reproduce**<br/>
Specify the necessary steps to reproduce the behavior. For example,
supply the setup.py command used for building if there is a build error,
or the steps taken when using the PyNE that produced the error.

**Expected Behavior**<br/>

**Screenshots or Code Snippets**<br/>
If applicable, add screenshots or snippets of code and error messages to help explain your problem.
Note, please do not include screenshots or snippets of code that is export controlled.

**Please complete the following information regarding your system:**<br/>
 - OS: [e.g. ubuntu Linux]
 - PyNE Version: [e.g. 0.7.1]
 - Versions of dependencies installed with: [e.g. HDF5 1.10]

**Additional Context**<br/>

I am trying to install pyne with conda on my macos M1. I have created a .yml as mentioned here https://github.com/pyne/pyne/issues/1452, but still getting the same error as given in the attachment. Can someone please help. 

This is the error I am getting. 

conda env update --file pyne.yml
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_update.py", line 132, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda_env/installers/conda.py", line 49, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 136, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 179, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 284, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 451, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1061, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 275, in get_reduced_index
        push_record(record)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 249, in push_record
        combined_depends = record.combined_depends
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/records.py", line 338, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 481, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 481, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 512, in _merge
        final = this_component.merge(that_component)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 787, in merge
        raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
    ValueError: Incompatible component merge:
      - 'mpi_openmpi_*'
      - 'mpi_openmpi_tempest*'

`$ /opt/miniconda3/bin/conda-env update --file pyne.yml --prune`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=nuclear
                CONDA_EXE=/opt/miniconda3/bin/conda
             CONDA_PREFIX=/opt/miniconda3/envs/nuclear
           CONDA_PREFIX_1=/opt/miniconda3
           CONDA_PREFIX_2=/opt/miniconda3/envs/tardis-nuclear
           CONDA_PREFIX_3=/opt/miniconda3
    CONDA_PROMPT_MODIFIER=(nuclear)
         CONDA_PYTHON_EXE=/opt/miniconda3/bin/python
               CONDA_ROOT=/opt/miniconda3
              CONDA_SHLVL=4
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/opt/miniconda3/envs/nuclear/bin:/opt/miniconda3/condabin:/opt/homebre
                          w/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:
                          /usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/var
                          /run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:
                          /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/v
                          ar/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleint
                          ernal/bin:/Users/anirbandutta/.iraf/bin:/Users/anirbandutta/.iraf/bin:
                          /Users/anirbandutta/.iraf/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : nuclear
    active env location : /opt/miniconda3/envs/nuclear
            shell level : 4
       user config file : /Users/anirbandutta/.condarc
 populated config files : /Users/anirbandutta/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : http://ssb.stsci.edu/astroconda/osx-64
                          http://ssb.stsci.edu/astroconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /Users/anirbandutta/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /Users/anirbandutta/.conda/envs
               platform : osx-64
             user-agent : conda/22.11.1 requests/2.26.0 CPython/3.9.5 Darwin/22.5.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

### LINKED ISSUE #1518: setup.py doesn't contain the 'require' section
**Describe the Bug**<br/>
The 'require' should contain all dependency packages.

For some reason the ubuntu.sh script has the dependency list, but this obviously isn't the right location.

### PR DESCRIPTION
**Pull request by ahnaf-tahmid-chowdhury**
## Description
This PR aims to redesign the PyNE build system using Scikit-Build, integrate MOAB and DAGMC support, and establish workflows for creating wheels and publishing them to PyPI. Additionally, it addresses the handling of the ENSDF Executables and the setup of nucdata during the build process.

## Motivation and Context
The motivation for this PR is to enhance the build system, enabling better support for modern tools and libraries, and streamline the distribution process. It also prepares PyNE for future updates and ensures its compatibility with new versions of ENSDF.

## Changes
This PR introduces the following changes:
- [x] Redesign of the build system using Scikit-Build.
- [x] Integration of MOAB support.
- [x] Integration of DAGMC support.
- [ ] Implementation of workflows for building wheels and publishing to PyPI.
- [ ] Handling of the ENSDF Executables, considering the potential for future updates.
- [ ] Setup of nucdata during the build process.

### Current behavior 
The existing build system might not be utilizing modern tools and libraries efficiently.

### New behavior
The redesigned build system will leverage Scikit-Build, include MOAB and DAGMC support, and provide workflows for creating and publishing wheels to PyPI. It will also address the handling of ENSDF Executables and nucdata setup.

## Other Information
- Please review and provide feedback on the proposed changes. Any additional suggestions or concerns are welcome.
- If there are any specific issues or challenges related to this PR, please mention them here.

## Changelog file
I have updated the [CHANGELOG](https://github.com/pyne/pyne/blob/develop/CHANGELOG.rst) file with this pull request.

### CODE REVIEW

**Comment by ahnaf-tahmid-chowdhury** [comment]
I am unfamiliar with Windows and macOS workflows. I have copied the commands from a DAGMC workflow, but it seems that Windows is not recognizing the Makefile. Any suggestions?

**Comment by ahnaf-tahmid-chowdhury** [comment]
I am getting the following error on `test_material.py`

```python
=================================== FAILURES ===================================
_______________________________ test_getitem_str _______________________________

    def test_getitem_str():
        mat = Material(nucvec)
        assert mat["U235"] == 1.0
>       pytest.raises(RuntimeError, lambda: mat["word"])

test_material.py:769: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_material.py:769: in <lambda>
    pytest.raises(RuntimeError, lambda: mat["word"])
material.pyx:1485: in pyne.material._Material.__getitem__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 0: invalid continuation byte

nucname.pyx:188: UnicodeDecodeError
=========================== short test summary info ============================
FAILED test_material.py::test_getitem_str - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 0: invalid continuation byte
======================== 1 failed, 107 passed in 1.04s =========================
Testing failed on test_material.py
Error: Process completed with exit code 1.
```
Am I missing any dependencies at build time?

**Comment by ahnaf-tahmid-chowdhury** [comment]
https://github.com/pyne/pyne/actions/runs/6181476561

It seems ubuntu is passing all builds. But getting some test fails

**Comment by bquan0** [comment]
@ahnaf-tahmid-chowdhury can you resolve the merge conflict? We want to see the github workflows run again and see what the errors are (if there are any). We want to change setup.py into a scikit build to hopefully fix the issues with [this conda feedstock PR.](https://github.com/conda-forge/pyne-feedstock/pull/83)

I saw in one of your comments that you were getting a `UnicodeDecodeError` in `test_material.py`. That error has been fixed by #1543 so hopefully there won't be any more test fails after resolving the merge conflict.

**Comment by ahnaf-tahmid-chowdhury** [comment]
@bquan0, apologies for the oversight! I'm currently working on a different branch to address those issues with a more robust approach. I'll be creating a new PR soon.

**Pull request closed without merging**
