### PR TITLE
Build System Overhaul - Including RPATH Fix

### PR DESCRIPTION
**Pull request by scopatz**
This basically rewrites the whole build system and flow for pyne. I have hopefully made more readable in the process.  The motivating reason for this is to correctly set the RPATH on the installed files.  This prevents the need for users to set `$LD_LIBRARY_PATH` or similar.  The shared objects *just* work (as far as I could test). The build flow now looks like the somewhat manic:

* setup.py, which calls
* cmake, make, and make install, which calls
* setup_sub.py.

setup.py is used as the name for the standard python installer interface. It is really a wrapper script around CMake (like Cyclus' install.py).  `make install` then calls setup_sub.py (which mainly calls distutils setup() function).  After this, `make install` repairs the RPATH on all shared objects.  

(Other) features include:

* No need for users to set `$LD_LIBRARY_PATH`!
* library is now at `$PREFIX/lib/libpyne.so`
* headers are now at `$PREFIX/include/pyne`
* It seems that the annoying bug with `nuc_data_make` needing to be rerun after each install is gone! I think that this is because I... 
* removed setuptools optional install dependency.
* Amazingly, this fits in less LOC
* updated cmake required version to 3.0.0

Let me know how it goes!

### CODE REVIEW

**Comment by scopatz** [comment]
Also, this include #905

**Comment by FlanFlanagan** [comment]
`robert@robert-VirtualBox:~/pyne$ sudo python3 setup.py install --user
/usr/bin/cmake
CMake command is
cmake .. -DCMAKE_INSTALL_PREFIX=/home/robert/.local -DPYTHON_EXECUTABLE=/usr/bin/python3

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  


-- Pyne platform defined as: __LINUX__
-- Build type: Release
-- CMAKE_INSTALL_RPATH: /home/robert/.local/lib:/usr/lib
-- CMake Install Prefix: /home/robert/.local
-- Dependency Root Dir (DEPS_ROOT_DIR): /usr
-- Dependency Hints (DEPS_HINTS): HINTS;/usr
-- Dependency Binary Hints (DEPS_BIN_HINTS): HINTS;/usr;/usr/bin
-- Dependency Library Hints (DEPS_LIB_HINTS): HINTS;/usr;/usr/lib
-- Dependency Include Hints (DEPS_INCLUDE_HINTS): HINTS;/usr/include
--    HDF5 Root: 
--    HDF5 Include directory: /usr/include/hdf5/serial
--    HDF5 Library directories: /usr/lib/x86_64-linux-gnu/hdf5/serial
--    HDF5 Libraries: 
--    HDF5 High Level Libraries: 
-- Could NOT find MOAB (missing:  MOAB_LIBRARY MOAB_INCLUDE_DIR) 
-- MOAB Found: FALSE
-- PYTHON_EXECUTABLE: /usr/bin/python3
-- PYTHON_SITE_PACKAGES: /home/robert/.local/local/lib/python3.5/dist-packages
-- NUMPY_VERSION_STRING = 1.11.3
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES: /usr/lib/gcc/x86_64-linux-gnu/5/usr/lib/x86_64-linux-gnu/usr/lib/lib/x86_64-linux-gnu/lib
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES: gfortranmquadmathmc
CMAKE_Fortran_COMPILER full path: /usr/bin/f95
Fortran compiler: f95
No optimized Fortran compiler flags are known, we just try -fpic...
-- NUMPY_VERSION_STRING = 1.11.3
-- F2PY Executable: /usr/bin/f2py
-- F2PY Version: 2
-- Include paths for /home/robert/pyne/src: /home/robert/.local/lib/python3.5/site-packages/numpy/core/include;/home/robert/pyne/build/pyne;/home/robert/pyne/src
-- Include paths for /home/robert/pyne/pyne: /home/robert/.local/lib/python3.5/site-packages/numpy/core/include;/home/robert/pyne/build/pyne;/home/robert/pyne/src
-- F2PY F90 FLAGS: 
-- Include paths for /home/robert/pyne/pyne/xs: /home/robert/.local/lib/python3.5/site-packages/numpy/core/include;/home/robert/pyne/build/pyne;/home/robert/pyne/src
-- Configuring done
-- Generating done
-- Build files have been written to: /home/robert/pyne/build
[  0%] Built target ReplicatePythonSourceTree
[  3%] Built target alphad
[  4%] Building CXX object src/CMakeFiles/pyne.dir/data.cpp.o
In file included from /home/robert/pyne/src/data.cpp:3:0:
/home/robert/pyne/src/data.h:20:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
src/CMakeFiles/pyne.dir/build.make:86: recipe for target 'src/CMakeFiles/pyne.dir/data.cpp.o' failed
make[2]: *** [src/CMakeFiles/pyne.dir/data.cpp.o] Error 1
CMakeFiles/Makefile2:180: recipe for target 'src/CMakeFiles/pyne.dir/all' failed
make[1]: *** [src/CMakeFiles/pyne.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

--------------------

If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http://pyne.io

--------------------
Traceback (most recent call last):
  File "setup.py", line 442, in <module>
    main()
  File "setup.py", line 415, in main
    main_safe(ns)
  File "setup.py", line 407, in main_safe
    main_body(ns)
  File "setup.py", line 390, in main_body
    rtn = subprocess.check_call(['make'] + ns.make_args, cwd=ns.build_dir)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
`

I'm showing this error locally, which I am not seeing on develop locally.

**Comment by scopatz** [comment]
Where is your HDF5 installed?  You may need to provide the path via the  `--hdf5-root` option

**Comment by scopatz** [comment]
Trying to trigger circle here

**Comment by scopatz** [comment]
Ok! @FlanFlanagan @makeclean @gonuke - this finally works!

**Comment by scopatz** [comment]
Also note that I have included some new fixes for the test suite that @makeclean and others have run into with newer versions of numpy

**Comment by FlanFlanagan** [comment]
Getting a new error, with lhdf5 even with directed to my hdf5 directory (the old error is gone). This may only be a local error so I'm going to keep working at it.

**Comment by FlanFlanagan** [comment]
-- LIBS: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- Include paths for /home/robert/pyne/src: /usr/lib/x86_64-linux-gnu/include;/usr/include/hdf5/serial;/home/robert/.local/lib/python3.5/site-packages/numpy/core/include;/home/robert/pyne/build/pyne;/home/robert/pyne/src
-- Include paths for /home/robert/pyne/pyne: /usr/lib/x86_64-linux-gnu/include;/usr/include/hdf5/serial;/home/robert/.local/lib/python3.5/site-packages/numpy/core/include;/home/robert/pyne/build/pyne;/home/robert/pyne/src
-- F2PY F90 FLAGS: 
-- Include paths for /home/robert/pyne/pyne/xs: /usr/lib/x86_64-linux-gnu/include;/usr/include/hdf5/serial;/home/robert/.local/lib/python3.5/site-packages/numpy/core/include;/home/robert/pyne/build/pyne;/home/robert/pyne/src
-- Configuring done
-- Generating done
-- Build files have been written to: /home/robert/pyne/build
[  0%] Built target ReplicatePythonSourceTree
[  3%] Built target alphad
[  4%] Linking CXX shared library libpyne.so
/usr/bin/ld: cannot find -lhdf5
/usr/bin/ld: cannot find -lhdf5
collect2: error: ld returned 1 exit status
src/CMakeFiles/pyne.dir/build.make:1238: recipe for target 'src/libpyne.so' failed
make[2]: *** [src/libpyne.so] Error 1
CMakeFiles/Makefile2:180: recipe for target 'src/CMakeFiles/pyne.dir/all' failed
make[1]: *** [src/CMakeFiles/pyne.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by scopatz** [comment]
what is the command you are using to build and where does your hdf5 live?

**Comment by FlanFlanagan** [comment]
sudo python3 setup.py install --user --hdf5 /usr/lib/x86_64-linux-gnu/

It lives in /usr/lib/x86_64-linux-gnu/hdf5

Which I have also tried, same result.

**Comment by scopatz** [comment]
I think you need to set $LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial. this is a long standing issue that I can try to fix here.

**Comment by FlanFlanagan** [comment]
Doesn't seem to fix the issue. I should be pointing it to the libhdf5.so type files right?

**Comment by scopatz** [comment]
OK, I believe that I have pushed up a real fix for this issue.

**Comment by scopatz** [comment]
With this new fix, you should no longer need to set `$LD_LIBRARY_PATH` for HDF5

**Comment by FlanFlanagan** [comment]
This looks good to me!

**Review by FlanFlanagan — APPROVED** [review]

**Comment by gonuke** [comment]
It seems that this change has essentially removed all support for mesh in PyNE with the elimination of PyTAPS.  Meshing is a core capability for our group and we have a growing set of workflows based on the ability to manipulate mesh in PyNE.

It would have been preferable to have both Python2 and Python3 testing, the former retaining PyTAPS until we have an opportunity to replace with pymoab. (As was already underway in #900)

**Comment by scopatz** [comment]
Hi Paul, I'll put in a new PR to run circle on both ubuntu 16.04/pytaps and ubuntu 17.04 / no-pytaps post haste

**Comment by gonuke** [comment]
Super! Thanks :+1:

**Pull request merged**
