### PR TITLE
Now add normalization tally card when normalization factor != 1

### PR DESCRIPTION
**Pull request by bam241**
Adds the tally card if normalisation != 1

this should address #1155

### CODE REVIEW

**Comment by bam241** [comment]
is that the expected behavior ? @gonuke

**Comment by gonuke** [comment]
Makes sense to me - probably should see if @makeclean had something else in mind originally?

**Review by gonuke — APPROVED** [review]
Thanks @bam241 - this LGTM - still hoping for some input from @makeclean - or I'll look to merge next week

**Comment by makeclean** [comment]
Sorry for the delay! So the reason why it was originally > 0 is that a negative tally multiplier (in MCNP speak) means multiply by atomic density, I expect other MC codes have the similar side affects. I always figured that we would eventually have some infrastructure that would take care of knowing that the normalisation referred purely to the number of source particles per second, and then other code would know which cell the tally refers to, with knowledge of the atomic density, the type of tally, e.g. heat would eventually be able to deal with the edge cases. Therefore, the assumption here is that the normalisation should be greater than 0 since it refers to the true normalisation. 

What stopped progress dead (for me) is/was the limitation of Cubit groups, as an analyst one often wants better grouping of tallies for your down stream purpose. Now, of course with the right downstream infrastructure, one should usually be able to combine the tally data into whatever you want.

**Comment by gonuke** [comment]
But the previous code was ">1" and not ">0"...

**Comment by gonuke** [comment]
I think the issue of `!=1` vs `>1` is sufficiently vague and this seems more consistent.

Thanks @bam241

**Pull request merged**
