### PR TITLE
Add pyne-amalgamation to travis

### LINKED ISSUE #641: add amalgamation test to CI
This should run `amalgamate.py` and compile a simple c++ test program.

### PR DESCRIPTION
**Pull request by brewlius-cesar**
Closes #641

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for putting in this PR @brewlius-cesar!

It looks like pyne-amalgamation has some hard coded paths in it https://travis-ci.org/pyne/pyne/jobs/61879761#L2937

**Comment by brewlius-cesar** [comment]
@scopatz I updated pyne-amalgamation so that "BASE" can be set in the environment.  I can submit a PR for this too if this is the preferred solution, see: brewlius-cesar/pyne-amalgamation@479a7f406

I'll need to update the clone URL in this repository then too

**Comment by scopatz** [comment]
Hi @brewlius-cesar - yes, please submit a PR to the pyne-amalgamation repo too.  Thanks!

**Comment by scopatz** [comment]
Relaunching with new alamgamation.

**Comment by scopatz** [comment]
All systems go! Thanks @brewlius-cesar!

**Comment by scopatz** [comment]
Are you on the dev mailing list @brewlius-cesar?

**Comment by brewlius-cesar** [comment]
Just subscribed.

**Comment by scopatz** [comment]
Awesome!

**Pull request merged**
