### PR TITLE
Isolate iMesh imports and calls to pyne.mesh

### PR DESCRIPTION
**Pull request by pshriwise**
This PR isolates as many references to iMesh as possible in preparation for a pyne.mesh implementation supported by pymoab. 

This addresses issues #951 #952 #953 #954 #949 #957 #980 #956.

### CODE REVIEW

**Comment by gonuke** [comment]
Is this still relevant @pshriwise ?

**Comment by pshriwise** [comment]
It could be. But it may be best to do all of the PyMOAB-related changes in one PR at this point. I’ll leave it up you and CNERG.

**Comment by gonuke** [comment]
But your other branch includes all of this, right?

**Comment by pshriwise** [comment]
Yup!

**Comment by pshriwise** [comment]
Should we close this?

**Comment by gonuke** [comment]
I thought we might wait until we make the pymoab PR and then reference that in the message to close

**Comment by gonuke** [comment]
Close now @pshriwise ?

**Comment by pshriwise** [comment]
This is overridden by #1097.

**Pull request closed without merging**
