### PR TITLE
fixes render fail

### PR DESCRIPTION
**Pull request by scopatz**
as seen here: http://pyne.io/pyapi/xs/data_source.html#pyne.xs.data_source.SimpleDataSource.discretize

Didn't have time to re-implement latex.

### CODE REVIEW

**Comment by crbates** [comment]
is this the expected behavior of Travis? Looks good to me.

**Comment by scopatz** [comment]
We have bugs on develop that are causing issues on Travis, so it is known.

**Comment by scopatz** [comment]
But this really shouldn't affect those!

**Comment by crbates** [comment]
thanks @scopatz!

**Pull request merged**
