### PR TITLE
Updated install instructions to reflect conda-recipes changes

### PR DESCRIPTION
**Pull request by makoziol0**
It appears conda recipes changed to add a seperate folder for all python recipes. From the [github](https://github.com/conda/conda-recipes) for conda-recipes:

> This repository has grown to well over 500 packages, and we are doing some housekeeping. We are currently in the process of moving most/all python packages into the python root directory. From there, we'll continue tidying up the root diretory with categories as appropriate.

### CODE REVIEW

**Comment by katyhuff** [comment]
Thanks @makoziol0 . This simple change seems fine as it's just one line in the docs.

However, unfortunately, the tests seem to be failing.  I can't imagine your change has caused this.

At the moment, your PR branch is 1 commit ahead, 8 commits behind pyne:develop. Can you please merge the newest develop changes, and push those updates to your PR branch? This may fix the issue. At the very least, it should re-trigger new test run. 

```
cd pyne
git checkout develop
git remote add upstream git@github.com:pyne/pyne
git fetch upstream develop
git merge upstream develop
```


Pro-tip for the future, please develop new code on feature branches (with a command like `git checkout -b mattfeature`). Then, your changes will be in the new branch `mattfeature` (call it whatever you like, mattfeature is just an example), but you can have a clean develop branch to keep up to date and make comparisons with locally.

**Comment by makoziol0** [comment]
Fixed! Thank you!

**Comment by katyhuff** [comment]
@gonuke -- any objections to this one?

**Comment by makoziol0** [comment]
I mucked this up again. Will fix it again soon, sorry.

**Pull request closed without merging**
