### PR TITLE
Added examples and explanations

### PR DESCRIPTION
**Pull request by jinneykil**

### CODE REVIEW

**Comment by elliottbiondo** [comment]
Hi @jinneykil. Thanks for the updates. Since there were some changes to these notebooks recently, it looks like there are some merge conflicts with this pull request. You will have to resolve these manually before this gets merged in. Are you familiar with this process?

**Comment by jinneykil** [comment]
Hi! Sorry I'm not quite familiar with the process.

**Comment by elliottbiondo** [comment]
A good write-up about how to resolve merge conflicts appears [here](http://softwarecave.org/2014/03/03/git-how-to-resolve-merge-conflicts/). This process is normally very simple. However in this case, the merge conflicts appear in ipython notebooks, which may make the conflicts a bit more difficult to resolve. In this rare case, since the changes you made affect a relatively small number of lines, it may be easier to just redo your changes on an updated copy of the develop branch and submit a new pull request.

**Comment by rachelslaybaugh** [comment]
@jinneykil I can help you with the merge when you get a break from finals.

**Comment by jinneykil** [comment]
Thanks!

**Comment by dschwen** [comment]
I reworked this PR in https://github.com/dschwen/pyne/tree/fix_729, fixing the conflicts and removing unnecessary prompt number changes.
I'll make a new PR once the issues with the failing CI tests are fixed.

**Comment by scopatz** [comment]
Awesome :)

**Pull request closed without merging**
