### PR TITLE
R2S updates

### LINKED ISSUE #798: Typo in default name of photon source file in r2s
The default photon source file in the R2S scripts has an extra `1` at the end of the file name.

### PR DESCRIPTION
**Pull request by elliottbiondo**
Closes #798, #802, #803 and updates documentation accordingly.

@gonuke or @makeclean could review; probably want to get this in sooner rather than later, in light of the possibility of the more widespread use of this code.

### CODE REVIEW

**Comment by elliottbiondo** [comment]
Travis says:

```
$ git clone --depth=50 --branch=r2s_updates https://github.com/pyne/pyne.git pyne/pyne
Cloning into 'pyne/pyne'...
warning: Could not find remote branch r2s_updates to clone.
```

Anyone know what's going on?

**Comment by makeclean** [comment]
Looks good to me. Im not really familiar enough with PEP8 for style stuff, but functionally looks good to me.

**Comment by scopatz** [comment]
you can always run the pep8 command on the file.

**Comment by makeclean** [comment]
We should have a pep8 test bot, which would cause test failures if its non compliant

**Comment by scopatz** [comment]
I feel like that is a terrible idea. pep8 and flake8 tend to spit out a bunch of noise in addition to useful things.  Also it wouldn't work on the Cython, C++, or Fortran.

**Comment by scopatz** [comment]
That might have come off strongly :(.  Shoulders deep in proposal stuff. Sorry.

**Comment by scopatz** [comment]
What I meant to say is that I think it is a good idea in theory but wouldn't work in practice.  Hooking PyNE up to https://landscape.io/ or similar is better.  It wouldn't block, but it would let us know where we stand.

**Comment by makeclean** [comment]
Its alright, I just very quickly get miffed about style guide failures. If style is intrinstic to getting a PR accepted, we should have an automatic check thats all.

**Comment by scopatz** [comment]
Yeah, understood.  People can always set up git hooks locally to do this.  And I get miffed to.  This happened to me yesterday, https://github.com/scopatz/xonsh/pull/671 and I just. wasn't. getting. it. :)

**Comment by makeclean** [comment]
So it looks PEP8 compliant :) Thanks @elliottbiondo

**Pull request merged**
