### PR TITLE
auto update copyright year

### PR DESCRIPTION
**Pull request by epassaro**
## Description
Changes to `docs/conf.py` to automatically update the copyright year in the website.

## Motivation and Context
Related to #1347.

## Changes
Documentation update.

## Changelog file
All pull requests are required to update the [CHANGELOG](https://github.com/pyne/pyne/blob/develop/CHANGELOG.rst) file with the PR.  Your update can take different forms including:

* creating a new entry describing your change, including a reference to this pull request number
* adding a reference to your pull request number to an exist entry if that entry can include your changes

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks @epassaro for this suggestion.  Looking forward to merging it soon.  Please also add an entry to `CHANGELOG.rst` while we try to sort out why tests are suddenly failing ???

**Comment by bam241** [comment]
Thx for the update, we tend to forgot about those !

@epassaro the problem with the test is because you did not rebase your branch against the latest `develop` version, so you are running an old version of CI

as there is no conflict GitHub has not picked that up !

**Comment by epassaro** [comment]
Rebased and put this PR under the **Maintenance** section, is that ok? @gonuke @bam241

**Review by gonuke — APPROVED** [review]
Thanks again @epassaro - this looks good to merge

**Pull request merged**
