### PR TITLE
Update CI images to use Ubuntu 20.04 to remove version limits

### PR DESCRIPTION
**Pull request by gonuke**
## Description
Change CI images to be based on Ubuntu 20.04

## Motivation and Context
Ubuntu 18.04 is stuck on python 3.6 which imposes limitations on various python packages, requiring the build system to restrict to old python packages.  This is an attempt to make us more free from those limitations.

## Changes
Changes base repository to Ubuntu 20.04, largely to advance the base python version to 3.8

### CODE REVIEW

**Comment by gonuke** [comment]
Build & test is expected to fail here because:
* the new docker images have new names based on u20.04
* as soon as this PR is merged, the Build & Test needs to refer to those new images
* therefore, we have to update the image reference in the build & test workflow now, even though those images don't exist yet

**Comment by gonuke** [comment]
This has been shown to work at https://github.com/gonuke/pyne/actions/runs/2348068640

**Comment by ngranda** [comment]
Thanks, @gonuke. I'll go ahead and merge to get the new PyNE images

**Comment by shimwell** [comment]
Great to see the setuptools and tables limits removed. congrats

**Pull request merged**
