### PR TITLE
Docker build MOAB 5.2.1

### PR DESCRIPTION
**Pull request by AI-Pranto**
Docker build with MOAB 5.2.1

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks @AI-Pranto - I've relaunched the failing test... we have some unexplained random failures there that are usually resolved by relaunching.

**Comment by gonuke** [comment]
Looks like the test has passed :tada: 

We're going to have to do a round of testing with the updated PyNE and various build options, and then we'll merge this.

**Comment by bam241** [comment]
Just launched the test on the different docker images, 

merging when done :)

**Comment by bam241** [comment]
I pushed the new version of the docker images based on this PR.

I'll rerun all the CI-test to make sure everything is ok one last time.

I'll merge after those re-run are done.

**Comment by bam241** [comment]
thx @AI-Pranto for the contribution !

**Comment by bam241** [comment]
LGTM!
thx @AI-Pranto

**Pull request merged**
