### PR TITLE
Add input check ebins

### PR DESCRIPTION
**Pull request by zxkjack123**
There are four input files for r2s photon transport (input, geom.h5m, source.h5m and e_bounds). Users sometimes forget to put `e_bounds` in the working directory and therefore cause a segmentation fault without the message of missing `e_bounds`.

This PR adds error message when the `e_bounds` is missing (or no read permission).

### CODE REVIEW

**Comment by ljacobson64** [comment]
LGTM. Not really sure how I would go about testing this though

**Comment by gonuke** [comment]
Not sure we can test with CI, but has someone tested what happens when you "throw" into MCNP (FORTRAN)?

**Comment by ljacobson64** [comment]
This is now what it looks like if there's no `e_bounds` file:
```
 mcnp     ver=5    , ld=02/23/19  02/23/19 11:40:22                   
Loading file geom.h5m
Initializing the GeomQueryTool...
Using faceting tolerance: 0.001
Building OBB Tree...
Implicit Complement assumed to be Vacuum
 This problem is using DAGMC version    3.100 w/ DagMC r   0
Going to write an lcad file = lcad
Writing Materials ...
Using default writer WriteHDF5 for file fcad 
          Thread Name & Version = MCNP5, 1.60
          Copyright LANS/LANL/DOE - see output file
                                  _                                      
            ._ _    _  ._   ._   |_                                      
            | | |  (_  | |  |_)   _)                                     
                            |                                            
  
 
  comment.  photon   importances have been set equal to 1.                                                               
           1           1           1           1           2
DAGMC tally 24 has these 2 energy bin boundaries: 
     0.001
     1e+36
tot bin: no
Creating dagmc mesh tally24, input: tally.h5m, output: pflux_mesh.h5m
    Tally range has psize: 1
  There are 38540 tetrahedrons in this tally mesh.
  Tally mesh has 78830 triangles.  Building KD tree of size 117370... done.

 comment. using random number generator  1, initial seed = 496125763           
Set overlap thickness = 0.001
 imcn   is done


                              ctm =        0.00   nrn =                 0
 dump    1 on file runtpe   nps =           0   coll =                0
 xact   is done

 cp0 =   0.17
terminate called after throwing an instance of 'std::invalid_argument'
  what():  File e_bounds not found or no read permission

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x91ecca in ???
#1  0x91e353 in ???
#2  0xcecc1f in ???
#3  0xcecbc7 in ???
#4  0xcecfc0 in ???
#5  0xcc3664 in ???
#6  0xc2ff75 in ???
#7  0xc2ffc0 in ???
#8  0xc2fc33 in ???
#9  0x69cb26 in ???
#10  0x7051bc in ???
#11  0x5e8978 in ???
#12  0x5ad214 in ???
#13  0x4ae27f in ???
#14  0x5d61eb in ???
#15  0x514abf in ???
#16  0x4e97a3 in ???
#17  0x4e9daa in ???
#18  0xcdc5e8 in ???
#19  0x40aae9 in ???
```

**Comment by ljacobson64** [comment]
I was going to suggest using something like this:
```
throw pyne::FileNotFound(e_bounds_file);
```

instead of using `std::invalid_argument`, but for whatever reason that just makes nonsense characters appear on the screen.

**Comment by ljacobson64** [comment]
@zxkjack123 I am going to suggest the following line instead:
```
throw std::runtime_error("File " + e_bounds_file + " not found or no read permission");
```

**Comment by zxkjack123** [comment]
Thanks @ljacobson64 . Below is the new error message after the adoption of your suggestion:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  File e_bounds not found or no read permission

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7FDF1A83AE08
#1  0x7FDF1A839F90
#2  0x7FDF19BE94AF
#3  0x7FDF19BE9428
#4  0x7FDF19BEB029
#5  0x7FDF1A22384C
#6  0x7FDF1A2216B5
#7  0x7FDF1A221700
#8  0x7FDF1A221918
#9  0x408CBC in read_e_bounds
#10  0x40B902 in sampling_setup_
#11  0x460AFF in source_
#12  0x5365EC in startp_
#13  0x41BC35 in hstory_
#14  0x42CD98 in trnspt_
#15  0x504BD7 in mcrun_
#16  0x420616 in MAIN__ at main.F90:?
Aborted (core dumped)
```

**Comment by zxkjack123** [comment]
Opps, something wrong here.

**Pull request closed without merging**
