### PR TITLE
Remove deprecated U mode in file open

### PR DESCRIPTION
**Pull request by gonuke**
This mode is now default and the input is deprecated.

### CODE REVIEW

**Comment by gonuke** [comment]
This PR breaks python2 support.  In Python2, you have to explicitly choose to open in universal newline mode, while in python 3 you do not.  We have three choices:
1. merge this and say goodbye to Python 2
2. leave this unmerged and live with warnings about deprecation (we can 
3. add some (complicated?) logic to handle both cases...

**Comment by gonuke** [comment]
I'm taking this out of the 0.7 release, we can live with warnings there

**Comment by gonuke** [comment]
Now that we're officially done with Python 2 - we can merge this....

**Comment by gonuke** [comment]
but this will officially break python 2 for ever... it is the point of no return.

**Comment by kkiesling** [comment]
> but this will officially break python 2 for ever... it is the point of no return.

we made the community decision back in 2017 and python 2 is officially deprecated- time to go past the point of no return.

**Comment by gonuke** [comment]
> > but this will officially break python 2 for ever... it is the point of no return.
> 
> we made the community decision back in 2017 and python 2 is officially deprecated- time to go past the point of no return.

Yup - then we should stop testing on python 2 in CI (post-release)

**Comment by kkiesling** [comment]
I am fine with merge failed python 2 CI since this is expected but we should immediately remove python 2 testing in CI

**Pull request merged**
