### PR TITLE
Fixing ALARA matlib error

### PR DESCRIPTION
**Pull request by elliottbiondo**
In ALARA matlib files, compositions are specified in mass percent, not mass density.
http://alara.engr.wisc.edu/users.guide.html/support.htm#ml

### CODE REVIEW

**Comment by scopatz** [comment]
CI failure :(

**Comment by elliottbiondo** [comment]
Same error:

```
ImportError: /home/travis/miniconda/envs/_build/lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /home/travis/miniconda/envs/_build/lib/python2.7/site-packages/pyne-0.5.0rc1-py2.7.egg/pyne/../lib/libpyne.so)
```

**Comment by scopatz** [comment]
Yeah, so I think this needs to be fixed. @makeclean has opened up some other issues related to this.

**Comment by makeclean** [comment]
Ok, looks good. CI Success!

**Comment by wbinventor** [comment]
Was the error related to gfortran ever fixed? I am running into this very same issue. I've installed the latest version of PyNE from the develop branch on two separate machines running Ubuntu 14.04 and 15.10, each with Miniconda for Python 2.7.11. In each case I see the following error when trying to import `pyne`:

``` ipython
In [1]: import pyne
/home/wboyd/anaconda2/lib/python2.7/site-packages/pyne/__init__.py:15: Warning: Error importing PyNE: you should not try to import PyNE from its source directory; please exit the PyNE source tree, and relaunch your python interpreter from there.
  warn(msg, Warning)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-72ad7ee3f3d8> in <module>()
----> 1 import pyne

/home/wboyd/anaconda2/lib/python2.7/site-packages/pyne/__init__.py in <module>()
      8 
      9 try:
---> 10     from .pyne_config import *
     11 except ImportError:
     12     msg = ("Error importing PyNE: you should not try to import PyNE from "

ImportError: /home/wboyd/anaconda2/lib/../lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /home/wboyd/anaconda2/lib/libpyne.so)
```

Note that when this was run I was _not_ inside of the PyNE source directory. In addition, I tried installing PyNE with conda as instructed from the documentation but it led to the same issue.

**Pull request merged**
