### PR TITLE
Ensdf pyne data

### PR DESCRIPTION
**Pull request by gonuke**
sample ESNDF data has been placed on the data repo and the code that referenced it updated.

### CODE REVIEW

**Comment by ngranda** [comment]
LGTM!

**Comment by gonuke** [comment]
I might need to update for conflicts here

**Comment by gonuke** [comment]
Feel free to do a review and approve it that way

**Review by ngranda — APPROVED** [review]
LGTM! I'll merge after you rebase. Thanks @gonuke.

**Pull request merged**
