### PR TITLE
pep8 format on all py files

### PR DESCRIPTION
**Pull request by shimwell**
## Description
As requested in PR #1435 this PR changes the code to match pep formatting. This is the default pep8 formatting for black but there are options like line-length, quote style if prefered.

Interestingly this showed up a few parts of the code that were still in Python 2.
I noticed a few print statements in ```docs/sphinxext/ipython_directive.py``` that were missing brackets that python3 requires.
I have added brackets to these print statements.
I guess this highlights the usefulness of bringing in some automatic pep8 formatting.
Screenshot from 2022-02-08 12-42-09

Screenshot from 2022-02-08 12-43-56

Screenshot from 2022-02-08 12-43-09

For interest 140 files had pep8 improvements but 13 files were perfectly formatted :tada:

Perhaps perfect is the wrong word there as that is subjective. Part of the motivation for uncompromising pep8 formatting is just to remove the time spent on formatting discussions and let us focus on the code.

## Motivation and Context
Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.

This PR gives use a preview of the changes that would be brought about if PR #1435 is merged

## Changes
What kind of change does this PR introduce? (Bug fix, feature, documentation update...)
pep8 formatting

## Behavior
What is the current behavior? What is the new behavior?
no change

## Other Information
Other relevant information to this pull request.
related to #1435 

## Changelog file
All pull requests are required to update the [CHANGELOG](https://github.com/pyne/pyne/blob/develop/CHANGELOG.rst) file with the PR.  Your update can take different forms including:

* creating a new entry describing your change, including a reference to this pull request number
* adding a reference to your pull request number to an exist entry if that entry can include your changes

### CODE REVIEW

**Comment by shimwell** [comment]
Test failed the first time as I forgot to include the change log entry.

**Comment by gonuke** [comment]
Perhaps we can wait and do this as the last step before the release as this will introduce a lot of conflicts with the release candidate.

With my merged PR #1434 - we might actually be ready to release, finally!!

**Comment by shimwell** [comment]
just resolving a merge conflict

**Comment by gonuke** [comment]
Thanks @shimwell - I'll go ahead and merge this.  It passes tests and I'm sure no-one will review all ... <checks notes> ... 22k line changes.

**Pull request merged**
