### PR TITLE
try to build both python 2 and 3 on circle

### PR DESCRIPTION
**Pull request by scopatz**
CC @gonuke @FlanFlanagan

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @ @gonuke @makeclean, I am now getting a couple of r2s errors in the Python 2 tests.  Are these expected? Any ideas on how to fix?

**Comment by makeclean** [comment]
Having merged #901 you should probably rebase to get the python2 tests working

**Comment by scopatz** [comment]
OK, I have merged from develop.

**Comment by scopatz** [comment]
Still seeing some r2s errors here.

**Comment by makeclean** [comment]
Ah, the issue is that someone modified the test program to run nose_tests. It should be running ./travis-run-tests.sh. When you run travis-run-tests, those r2s failures go away. Notice that the failures are from the multiprocessing pool functions. This is why travis-run-tests.sh was originalyl written. Modify that then the issue should go away. I'll make a new PR that fixes this.

**Comment by scopatz** [comment]
Hi @makeclean - this is now giving `./travis-run-tests.sh: line 4: test_command: command not found` oddly...

**Comment by makeclean** [comment]
Awesome, that fixed all the R2S tests. That material test failure seems to be common to some of other material changes going on with decay. I would call this done :)

**Comment by scopatz** [comment]
Yay! The tests on this finally pass.

**Comment by makeclean** [comment]
bitmoji

**Comment by scopatz** [comment]
Please feel free to merge @makeclean :)

**Pull request merged**
