### PR TITLE
Pyne user passwd

### PR DESCRIPTION
**Pull request by bam241**
Add the password of the "pyne-user" for the VB on the website...

This was a problem in the [pyne mailing-list](https://groups.google.com/forum/#!topic/pyne-users/8Gg-g2dx4pk)

### CODE REVIEW

**Comment by bam241** [comment]
@gonuke any idea why I closed this ?

**Comment by gonuke** [comment]
Didn't we post a new VB? with a new password?

**Comment by bam241** [comment]
I can't remember... 
I guess I will have to check the VB password :)

**Comment by gonuke** [comment]
thanks @bam241

**Pull request merged**
