### PR TITLE
fixes to get ahot semi-working on mac

### PR DESCRIPTION
**Pull request by crbates**
This serves as documentation for a sunday evening experiment. More work is needed to track down the random crashes.

### CODE REVIEW

**Comment by scopatz** [comment]
What are the random crashes exactly? What triggers them? Just curious...

**Comment by crbates** [comment]
not sure exactly `nosetests` just exits at random during the ahot tests. Some tests seem to have a higher probability of causing the crash. I have skipped those. This doesn't work on batlab because gfortran on osx is too old.

**Comment by makeclean** [comment]
@crbates please rebase against develop and push

**Comment by makeclean** [comment]
4 years since last comment, close

**Pull request closed without merging**
