### PR TITLE
Return pointer for the member variable in ValueError::what()

### PR DESCRIPTION
**Pull request by pshriwise**
A proposed fix for #1357.

The main change here is that the `"ValueError: "` prefix is added in the constructor instead of in the `::what` method. The main consequence here is that extracting the original message becomes more tricky, but in practice, I think this an exceedingly rare use case for the object.

Just a note that this is _fix_, but the best long term solution may be to inherit from `std::runtime_error` or the like, which manages the error message and any exceptions that may arise from the internal string's construction (i.e. `ValueErrror::message`) as well.

### CODE REVIEW

**Comment by gonuke** [comment]
Another approach would be to have 2 member variables, one with the user message & one with the full message. 

I don't have a strong feeling for that, but thought I'd mention it before merging

**Comment by pshriwise** [comment]
A fair point. If you'd prefer that approach I can update it. Seeing as these are typically used immediately after construction it probably doesn't matter much in practice. I thought it would be more simple to keep the one member variable.

**Comment by gonuke** [comment]
This solution is fine.  Thanks @pshriwise

**Comment by gonuke** [comment]
Looks like it needs a changelog entry

**Review by bam241 — APPROVED** [review]
LGTM!
thx @pshriwise

**Comment by bam241** [comment]
test are failing because you're following your PyNE Fork on CI....

**Comment by pshriwise** [comment]
Just unfollowed the project... it looks like many of the jobs ran successfully though? Does only the `py3_dagmc_pymoab_openmc_test` job need me to unfollow?

**Comment by pshriwise** [comment]
Seems like this is looking good now @gonuke @bam241. Thanks for the reviews!

**Comment by bam241** [comment]
Merging after CI passes
Thx @pshriwise

**Comment by bam241** [comment]
Merging !

**Pull request merged**
