### PR TITLE
add more guidance to the required format of the MCNP meshtal file

### PR DESCRIPTION
**Pull request by gonuke**
The meshtal reader only supports a particular format of mesh tally output - this PR makes that clear in the help string of this script.

### CODE REVIEW

**Comment by gonuke** [comment]
This seems to be failing on a timeout with accessing data - anyone know how to fix this?  It's a small documentation change, so I'm confused about why this is happening?

**Comment by pshriwise** [comment]
@gonuke I've seen that too on a few other PRs. I've been restarting them when I see this happening. It seems the links aren't super reliable and this probably isn't related to the change here.

**Comment by zxkjack123** [comment]
@gonuke There are too many files to download during the tests. It will report an error even if there is only one timeout failure. So, the timeout failures happen a lot.
I found that several links are to be blamed for most cases.  I think adding some mirror backup links in pyne/data for these files with high failure probability would reduce the timeout failure.

**Comment by gonuke** [comment]
Looks like this finally passed tests...

**Comment by zxkjack123** [comment]
@gonuke LGTM.

**Pull request merged**
