### PR TITLE
Examples updates: material_library & material

### PR DESCRIPTION
**Pull request by opotowsky**
Two example notebooks listed in issue #1276 are updated: materials and material_library.

### CODE REVIEW

**Comment by opotowsky** [comment]
Waiting for merge of #1279 to update changelog

**Comment by opotowsky** [comment]
@ZoeRichter @ngranda this one is ready WOO

**Comment by gonuke** [comment]
Can you please run all these NBs again after the mass data update, please?

**Review by ngranda — APPROVED** [review]
LGTM, I'll wait for tests

**Comment by gonuke** [comment]
Thanks @opotowsky

**Pull request merged**
