### PR TITLE
maintainence - IGNORE

### PR DESCRIPTION
**Pull request by kkiesling**
just a maintainence PR to see which tests are failing on CI. (do not merge)

### CODE REVIEW

**Comment by kkiesling** [comment]
@elliottbiondo and @makeclean, as per request of Anthony, here is a PR to figure out which tests fail on Travis CI.

**Comment by scopatz** [comment]
Here is a Python 3 error:

```bash
======================================================================

ERROR: test_dagmc.test_list_functions

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/miniconda/lib/python3.4/site-packages/nose-1.3.4-py3.4.egg/nose/case.py", line 198, in runTest

self.test(*self.arg)

File "/home/travis/build/pyne/pyne/tests/test_dagmc.py", line 307, in test_list_functions

r = results.get()

File "/home/travis/miniconda/lib/python3.4/multiprocessing/pool.py", line 599, in get

raise self._value

multiprocessing.pool.MaybeEncodingError: Error sending result: '[dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]), dict_keys([1, 2, 3, 4])]'. Reason: 'PicklingError("Can't pickle <class 'dict_keys'>: attribute lookup dict_keys on builtins failed",)'

----------------------------------------------------------------------

Ran 19 tests in 9.020s
```

**Comment by scopatz** [comment]
Oh and weird, the Python 2 errors are in bins:

```python
Testing test_bins.py:

................FF..

======================================================================

FAIL: test_bins.test_pointwise_linear_collapse(array([ 0., 1.]), array([ 0. , 0.75]), array([ 0., 1.]), [0.375])

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

self.test(*self.arg)

File "/home/travis/build/pyne/pyne/tests/test_bins.py", line 42, in check_pointwise_linear_collapse

assert_array_almost_equal(exp, obs)

File "/home/travis/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal

precision=decimal)

File "/home/travis/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare

raise AssertionError(msg)

AssertionError:

Arrays are not almost equal to 6 decimals

(mismatch 100.0%)

x: array([ 0.375])

y: array([ 0.625])

======================================================================

FAIL: test_bins.test_pointwise_linear_collapse(array([ 1., 0.]), array([ 0.75, 0. ]), array([ 1., 0.]), [0.375])

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

self.test(*self.arg)

File "/home/travis/build/pyne/pyne/tests/test_bins.py", line 42, in check_pointwise_linear_collapse

assert_array_almost_equal(exp, obs)

File "/home/travis/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal

precision=decimal)

File "/home/travis/miniconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare

raise AssertionError(msg)

AssertionError:

Arrays are not almost equal to 6 decimals

(mismatch 100.0%)

x: array([ 0.375])

y: array([ 0.625])

----------------------------------------------------------------------

Ran 20 tests in 0.019s

FAILED (failures=2)

Testing failed on test_bins.py
```

**Comment by elliottbiondo** [comment]
@kkiesling and I just looked at this.

"'PicklingError("Can't pickle <class 'dict_keys'>: attribute lookup
dict_keys on builtins failed",)"

is quite mysterious, as it appears @kkiesling fixed this in #699, by casing
the dict_keys into a list. Maybe this some sort of Python 3 subtly that I
don't quite grasp.

I have observed failures with pyne.bins before: I think there may be some
sort of non-deterministic race condition.

**Comment by kkiesling** [comment]
@scopatz, neither @elliottbiondo or I know why those python 2 tests are randomly occurring (from what Elliott said, that seems like nothing new). The error occurring in the python 3 tests should have already been fixed with my PR #699 commit 7c92552 on 3/18. You and I had a conversation about this pickling error during that PR.

**Comment by kkiesling** [comment]
Ya, I don't understand why that pickling error is now suddenly occurring on Travis when it that function is clearly returning a list and not some dict.keys() object.

**Comment by scopatz** [comment]
It is actually returning a list of dict-keys objects, not a list of the keys :) see:

```python
[dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]), dict_keys([1, 2, 3, 4])]
```

**Comment by kkiesling** [comment]
Right. What it should be returning is a list of lists as such [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], [1, 2, 3, 4]]. Based on how dagmc.get_surface_list() is written, the following should be returned:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
But for some reason, that is not happening here. The same thing should occur with dagmc.get_volume_list(). However, according to the test, it is still returning a dict_keys() object even though the functions don't return that.  @elliottbiondo and I tested using list(dict.keys()) in python 3 and it definitely returns a list, not a dict_keys() object. What I am saying is that this has already been addressed and I am not sure why it seems to be ignoring the fact that this was already fixed.

**Comment by scopatz** [comment]
Ok this is because it was pulling from my ci branch.  pyne/pyne-ci#28 provides the fix.

**Comment by scopatz** [comment]
Ok So now with the fix in, we have a new fluka error on Python 3 and the same error on Python 2:

```console
Testing test_fluka.py:

/home/travis/miniconda/lib/python3.4/site-packages/pyne-0.5.0rc1-py3.4.egg/pyne/fluka.py:26: QAWarning: the PyTAPS optional dependency could not be imported. Some aspects of the mcnp module may be incomplete.
QAWarning)
/home/travis/miniconda/lib/python3.4/site-packages/pyne-0.5.0rc1-py3.4.egg/pyne/mesh.py:12: QAWarning: pyne.mesh is not yet QA compliant.
warn(__name__ + " is not yet QA compliant.", QAWarning)
/home/travis/miniconda/lib/python3.4/site-packages/pyne-0.5.0rc1-py3.4.egg/pyne/mesh.py:18: QAWarning: the PyTAPS optional dependency could not be imported. Some aspects of the mesh module may be incomplete.
"Some aspects of the mesh module may be incomplete.", QAWarning)
/home/travis/miniconda/lib/python3.4/importlib/_bootstrap.py:321: QAWarning: pyne.data is not yet QA compliant.
return f(*args, **kwds)
/home/travis/miniconda/lib/python3.4/importlib/_bootstrap.py:321: QAWarning: pyne.material is not yet QA compliant.
return f(*args, **kwds)
SSSE
======================================================================
ERROR: test_fluka.test_mesh_write
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/miniconda/lib/python3.4/site-packages/nose-1.3.4-py3.4.egg/nose/case.py", line 198, in runTest
self.test(*self.arg)
File "/home/travis/build/pyne/pyne/tests/test_fluka.py", line 286, in test_mesh_write
usrbin_object = fluka.Usrbin(usrbin_file)
File "/home/travis/miniconda/lib/python3.4/site-packages/pyne-0.5.0rc1-py3.4.egg/pyne/fluka.py", line 55, in __init__
raise RuntimeError("PyTAPS is not available, "
RuntimeError: PyTAPS is not available, unable to create Meshtal.
----------------------------------------------------------------------
Ran 4 tests in 0.002s
FAILED (SKIP=3, errors=1)
Testing failed on test_fluka.py
```

**Comment by scopatz** [comment]
Hi @kkiesling - So from the current build issues now seem to be from fluka stuff that you implemented (so say @elliottbiondo and @makeclean).  You see the errors in the build of #705 (https://travis-ci.org/pyne/pyne/builds/56724604).  These should both be one line fixes (missing `assert_equals()` import, etc).  If you could fix these up, that would be awesome!  Thanks!

**Comment by kkiesling** [comment]
Yes! I saw this and then got sick and forgot about it. I'll get on this shortly. Thanks for the reminder.

**Comment by scopatz** [comment]
Thanks 1e9 @kkiesling!

**Pull request closed without merging**
