### PR TITLE
update tutorial to remove pytaps references

### LINKED ISSUE #1240: pytaps reference in the tutorials
The tutorials still use the old `pyne.Mesh` implementation based on `pytaps`

for example the usage of `m.mesh.getVtxCoords(ve)` in the `00-intro` tutorial is outdated.

One ned to update the tutorials to the last `pyne.Mesh` implementation based on `pymoab`

### PR DESCRIPTION
**Pull request by kkiesling**
This fixes one line in the intro tutorial to properly call the pyMOAB function rather than the pytaps function.

### CODE REVIEW

**Comment by kkiesling** [comment]
Can someone double check this works in python 3 (@lkissin2)?

**Comment by kkiesling** [comment]
fixes issue #1240

**Comment by opotowsky** [comment]
Could you update the base to be against the 0.7 RC branch? Also we have a section in the changelog on this topic (line 82 now), so this change could be added to that

**Comment by kkiesling** [comment]
@opotowsky - because of all the changes to the 0.7.0-rc branch I figured it would just be easier for whoever was fixing tutorials to  change that one function call. It looks like there are a ton of conflicts here now when I change the base branch.

**Comment by opotowsky** [comment]
Sounds good I'll do that!

**Comment by bam241** [comment]
@kkiesling can you check your change are included in @opotowsky PR #1282 ?
If so please close this :)

**Comment by kkiesling** [comment]
Yes.. changes have been included.. but I can't figure out how to close this from the app on my phone.

Nvm, found the button

**Pull request closed without merging**
