### PR TITLE
Fix PR #729

### PR DESCRIPTION
**Pull request by dschwen**
Closes #729

### CODE REVIEW

**Comment by scopatz** [comment]
Looks good, @dschwen. Waiting for CI

**Comment by dschwen** [comment]
Actually, this is not OK. Jupyter cannot open the modified notebooks. Let me see if I can fix this. I'll also add a travis test to validate the JSON wellformedness for the tutorial notebooks.

**Comment by scopatz** [comment]
OK, please ping when ready, then.

**Comment by dschwen** [comment]
@scopatz I think this is ready

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
