### PR TITLE
fixed bins error where memory beyond the array buffer was being read.

### PR DESCRIPTION
**Pull request by scopatz**
This was super nasty to find, and I am sorry everyone.  This one was totally my fault.  On the plus side, I have checked all the math again.

### CODE REVIEW

**Comment by scopatz** [comment]
Maybe @elliottbiondo wants to take a look.

**Comment by elliottbiondo** [comment]
Relaunching CI now that #709 has been merged.

**Comment by scopatz** [comment]
ping!

**Comment by elliottbiondo** [comment]
Alright looks good! Merged.

**Comment by scopatz** [comment]
Woohoo!

**Pull request merged**
