### PR TITLE
Fix reorder error. 

### LINKED ISSUE #1466: Fix member variable order to build with -Wreorder
I'm trying to build Pyne using MOOSE's environment, which passes the `-Wreorder` compile flag. This is hitting the following error:

```
/home/anovak/cardinal/contrib/DAGMC/src/pyne/pyne.h: In constructor 'pyne::Sampler::Sampler(std::string, std::string, std::vector<double>, std::string)':
/home/anovak/cardinal/contrib/DAGMC/src/pyne/pyne.h:6243:25: error: 'pyne::Sampler::e_bounds' will be initialized after [-Werror=reorder]
 6243 |     std::vector<double> e_bounds;  ///< Energy boundaries
      |
```

Solution is to just fix the member variable order in the header file.

### PR DESCRIPTION
**Pull request by aprilnovak**
Closes #1466

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks @aprilnovak - do you have any idea why this generates an error?

**Comment by aprilnovak** [comment]
Yes, the `-Wreorder` compilation flag checks that the order of members declared in a class definition matches that in the member initialization list of a class. The underlying reason for this flag is that, when a class member is declared, it's also initialized (most often to some unknown value, but you could also have something like `int a_ = 1;`. Later in the member initialization list, it's possible that member variable is used to initialize other members so the order could matter.

The particular fix here is that the order in the header file did not match the member initialization list.

**Comment by aprilnovak** [comment]
I think [this post](https://stackoverflow.com/questions/1828037/whats-the-point-of-g-wreorder#:~:text=The%20problem%20is,itself%20been%20initialised.) also does a good job of explaining it as well.

**Review by pshriwise — APPROVED** [review]
Thanks @aprilnovak! This is a pretty straightforward improvement, but I'll give it 24 hrs in case others have any additional comments/questions.

**Comment by gonuke** [comment]
Thanks again @aprilnovak - a new tip to remember for all our projects 😀 (as well as building with warnings on)

**Pull request merged**
