### PR TITLE
site packages location fix for Python 2

### PR DESCRIPTION
**Pull request by scopatz**
Hopefully this fixes the problem in #927 as reported by @kkiesling

### CODE REVIEW

**Comment by scopatz** [comment]
OK This looks like it works on CI!

**Comment by ljacobson64** [comment]
It seems to me like all the `.so` files are getting installed twice now: first by `setup_sub.py` and then again during `make install`. This is why everything still worked when I deleted the CMake lines that installed the libraries: they were already installed. They don't need to be installed twice, would you agree?

i.e. you'll see

```
copying build/lib.linux-x86_64-2.7/pyne/ace.so -> <install_prefix>/lib/python2.7/site-packages/pyne
```

and then later on you'll see

```
-- Installing: <install_prefix>/lib/python2.7/site-packages/pyne/ace.so
```

**Comment by scopatz** [comment]
> They don't need to be installed twice, would you agree?

So actually one of the major benefits of the refactor is that they are installed twice.  The first time that they are installed (by setup_sub.py), they have the wrong RPATH setting. Specifically they have the `CMAKE_BUILD_RATH`.  So if you were to use this version, you  would **need** to have LD_LIBRARY_PATH set to the build path or a similar place where the libs could be found.  This is unavoidable in Python (without a lot of hacks) because Python and setuptools and distutils do not have a mechanism to set the RPATH of extension modules. 

The second time they are installed, they are installed by CMake.  CMake, alternatively, gives you complete control over the RPATH at both build and install.  By reinstalling with CMake *after* the Python install, we are able to easily set the correct RPATH.

**Comment by scopatz** [comment]
Great question, btw @ljacobson64!

**Comment by ljacobson64** [comment]
I see... so there is a method to the madness! I'll merge this and rebase my PR and we can go from there.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
