### PR TITLE
added optional setuptools

### PR DESCRIPTION
**Pull request by scopatz**
Should have been done a while ago, given distutils lack of future support.

### CODE REVIEW

**Comment by jdangerx** [comment]
Looks like the CI isn't making it to the test phase. Not entirely sure why.

**Comment by scopatz** [comment]
Relaunching

**Comment by scopatz** [comment]
Actually what is the website?

**Comment by jdangerx** [comment]
Looks like a legit install error. The logs say:
`ImportError: libpyne.so: cannot open shared object file: No such file or directory`
and
`/slots/02/dir_5046/userdir/anaconda/lib/python3.4/site-packages/pyne-0.5.dev0-py3.4.egg/pyne/__init__.py:15: Warning: Error importing PyNE: you should not try to import PyNE from its source directory; please exit the PyNE source tree, and relaunch your python interpreter from there.`
Incidentally, this message is kind of misleading - though importing PyNE from /pyne will cause an import error, other things can do it too. I've been bit by this before. Maybe we should change the wording a bit?

**Comment by scopatz** [comment]
The dashboard is at http://gorgus.pyne.io/dashboard doh

**Comment by scopatz** [comment]
Uggh I think that this is a CI & setuptools related issue. The PR works just fine on my machine. Can you confirm?

**Comment by crbates** [comment]
I have the same problem as CI (and using macports Python not conda). I think it's because the relative path links get messed up since it's now in the egg folder but thats just a guess.

**Comment by scopatz** [comment]
Ohhh I have a fix for this

**Comment by scopatz** [comment]
Ok, the fix is in.  Hopefully it passes CI.

**Comment by crbates** [comment]
`ImportError: libpyne.so: cannot open shared object file: No such file or directory ` :(

**Comment by scopatz** [comment]
Hmm this works just fine on my computer.  Does it work locally for you @jdangerx or @crbates?

**Comment by crbates** [comment]
This doesn't work locally for me. I think it tries to outsmart cmake when re-linking libpyne (which ends up in `egg/lib/libpyne.*`) but it's not 100% clear

**Comment by scopatz** [comment]
Python packaging is so gross. I hate eggs, and not just because I am vegan.

**Comment by katyhuff** [comment]
:+1:

**Comment by scopatz** [comment]
Found this and their arrogance: https://pythonhosted.org/setuptools/setuptools.html#automatic-resource-extraction

After looking at this some more, I don't think that our cmake, make, setup strategy is going to work with modern setuptools.  We could add some sort of ridiculous awful hack that attempts to figure out where setup tools installed things and then move the lib and include dirs out of that directory into the prefix directory after install.  But frankly, I don't trust setuptools to not break things again.

A better strategy might be to move to a cmake, make, setup, make install strategy, where everything in the src dir gets installed with cmake and everything in the pyne dir is installed with setup (even if it was built with cmake).  

Also, do we need to install the fortran *.mod files? I don't think we do right now. Do this go into include or lib? Forgive my newbishness, my fortran knowledge starts at subroutines and ends at `!`

**Comment by makeclean** [comment]
For fortran I would suggest a route like we have for c++. We could chuck all the .o files into an archive .a file shove that into the lib.

As far as I remember the mod files are produced at compile time as a first step, used to make .o files and then are forgotten about.


Sent on a Sprint Samsung Galaxy Note® 3

<div>-------- Original message --------</div><div>From: Anthony Scopatz <notifications@github.com> </div><div>Date:02/02/2015  7:23 PM  (GMT-06:00) </div><div>To: pyne/pyne <pyne@noreply.github.com> </div><div>Cc:  </div><div>Subject: Re: [pyne] added optional setuptools (#652) </div><div>
</div>Found this and their arrogance: https://pythonhosted.org/setuptools/setuptools.html#automatic-resource-extraction

After looking at this some more, I don't think that our cmake, make, setup strategy is going to work with modern setuptools. We could add some sort of ridiculous awful hack that attempts to figure out where setup tools installed things and then move the lib and include dirs out of that directory into the prefix directory after install. But frankly, I don't trust setuptools to not break things again.

A better strategy might be to move to a cmake, make, setup, make install strategy, where everything in the src dir gets installed with cmake and everything in the pyne dir is installed with setup (even if it was built with cmake).

Also, do we need to install the fortran *.mod files? I don't think we do right now. Do this go into include or lib? Forgive my newbishness, my fortran knowledge starts at subroutines and ends at !

**Comment by scopatz** [comment]
> As far as I remember the mod files are produced at compile time as a first step, used to make .o files and then are forgotten about.

good to know.

**Comment by scopatz** [comment]
Moving to v0.6

**Pull request merged**
